x-defaults: &defaults
  restart: always
  init: true
  env_file:
    - .env

  environment: &environment
    DOCKER: true
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432

  logging:
    driver: 'json-file'
    options:
      max-size: '5m'
      max-file: '10'
      tag: '{{.Name}}'

  healthcheck: &healthcheck
    interval: 15s
    timeout: 7s
    retries: 3
    start_period: 10s

x-base: &base
  build: .
  user: node

services:
  postgres:
    <<: *defaults
    image: postgres:15.4-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      <<: *healthcheck
      test: ['CMD', 'nc', '-zv', 'localhost', '5432']

  cdn:
    <<: *defaults
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/cdn/nginx.conf:/etc/nginx/nginx.conf
      - cdn:/var/www/cdn
    healthcheck:
      <<: *healthcheck
      test: ['CMD', 'nc', '-zv', 'localhost', '80']

  api:
    <<: [*defaults, *base]
    command: pnpm turbo run dev --env-mode=loose --filter='@blms/api'
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0
      POSTGRES_HOST: postgres
      TYPESENSE_NODES: http://typesense:8108
    volumes:
      - ./apps/api:/home/node/apps/api
      - /home/node/apps/api/node_modules/
      - ./packages/service-content/src:/home/node/packages/service-content/src
      - ./packages/database/src:/home/node/packages/database/src
      - ./packages/schemas/src:/home/node/packages/schemas/src
      - ./packages/types/src:/home/node/packages/types/src
      - ./packages/service-user/src:/home/node/packages/service-user/src
      - cdn:$CDN_PATH
      - sync:${SYNC_PATH:-/tmp/sync}
      - ${OTS_PGP_KEY_PATH:-./key.asc}:/tmp/key.asc:ro
    depends_on:
      - typesense
      - postgres
    healthcheck:
      <<: *healthcheck
      test: ['CMD', 'nc', '-zv', 'localhost', '3000']

  web:
    <<: [*defaults, *base]
    command: pnpm turbo run dev --env-mode=loose --filter='@blms/web'
    ports:
      - 8181:8181
    volumes:
      - ./apps/web:/home/node/apps/web
      - ./packages:/home/node/packages
      - /home/node/apps/web/node_modules/
      - cdn:$CDN_PATH
    depends_on:
      - api
    healthcheck:
      <<: *healthcheck
      test: ['CMD', 'nc', '-zv', 'localhost', '8181']

  contribute:
    <<: [*defaults, *base]
    command: pnpm turbo run dev --env-mode=loose --filter='@blms/contribute'
    ports:
      - 8280:8280
    volumes:
      - ./apps/contribute:/home/node/apps/contribute
      - ./packages:/home/node/packages
      - /home/node/apps/contribute/node_modules/
    depends_on:
      - api
    healthcheck:
      <<: *healthcheck
      test: ['CMD', 'nc', '-zv', 'localhost', '8280']

  # https://typesense.org
  typesense:
    image: typesense/typesense:28.0
    ports:
      - 8108:8108
    container_name: typesense
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY:-xyz}
      - TYPESENSE_DATA_DIR=/usr/share/typesense/data
      - GLOG_minloglevel=2 # https://github.com/typesense/typesense/issues/475
    volumes:
      - typesense:/usr/share/typesense/data

volumes:
  typesense:
  corestore:
  postgres:
  cdn:
  sync:
