user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

# Import the JavaScript module
load_module /usr/lib/nginx/modules/ngx_http_js_module.so;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Use docker's DNS resolver
    resolver 127.0.0.11 ipv6=off;

    map "$time_iso8601:$msec" $time_iso8601_ms {
        ~(.+)\+00:00:.+(\..+) $1$2Z;
        ~(.+)(\+.+):.+(\..+)  $1$3$2;
    }

    map "$http_cf_connecting_ip" $real_ip {
        default $http_cf_connecting_ip;
        "" $http_x_real_ip;
    }

    log_format  main  '$time_iso8601_ms $request_id $real_ip $request_method "$request_uri" '
                      '$status $request_time $body_bytes_sent "$http_referer" "$http_user_agent"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    server {
        listen 80;
        server_name _;

        gzip on;
        gzip_disable "msie6";

        gzip_comp_level 6;
        gzip_min_length 1100;
        gzip_buffers 16 8k;
        gzip_proxied any;
        gzip_types
            text/plain
            text/css
            text/js
            text/xml
            text/javascript
            application/javascript
            application/x-javascript
            application/json
            application/xml
            application/rss+xml
            image/svg+xml/javascript;

        root /usr/share/nginx/html;

        # Match hashed assets and set cache control to immutable
        location ~ "^/assets/(?<filename>.+)\-(?<hash>[\w\-]{8})\.(?<extension>\w+)$" {
            expires 1y;
            # Cache-Control: public, immutable, stale-while-revalidate: 1 year, stale-if-error: 1 year
            add_header Cache-Control "public, immutable, stale-while-revalidate=31536000, stale-if-error=31536000";
            add_header X-Hash-Match $hash;
        }

        # Set the expires header to 30 minutes for all other files (path with a dot)
        location ~ ".*(\.).*$" {
            access_log off;
            expires 30m;
        }

        # Match the index.html and set the metadata
        location / {
            try_files /index.html =404;

            # Debugging headers
            add_header X-Index-Match "true" always;

            # X-Robot-Tag: noindex, nofollow - We do not want to index this project
            add_header X-Robots-Tag "noindex" always;

            # Set the expires header to 30 seconds
            expires 30s;
        }
    }
}
