// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources';

/** Identifier type for content.articles */
export type ArticlesId = number;

/** Represents the table content.articles */
export default interface Articles {
  id: ArticlesId;

  resource_id: ResourcesId;

  language: string;

  title: string;

  author: string;

  description: string | null;

  publication_date: Date | null;

  article_url: string;
}

/** Represents the initializer for the table content.articles */
export interface ArticlesInitializer {
  /** Default value: nextval('content.articles_id_seq'::regclass) */
  id?: ArticlesId;

  resource_id: ResourcesId;

  language: string;

  title: string;

  author: string;

  description?: string | null;

  publication_date?: Date | null;

  article_url: string;
}

/** Represents the mutator for the table content.articles */
export interface ArticlesMutator {
  id?: ArticlesId;

  resource_id?: ResourcesId;

  language?: string;

  title?: string;

  author?: string;

  description?: string | null;

  publication_date?: Date | null;

  article_url?: string;
}
