// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources';

/** Identifier type for content.books_localized */
export type BooksLocalizedLanguage = string;

/** Represents the table content.books_localized */
export default interface BooksLocalized {
  book_id: ResourcesId;

  language: BooksLocalizedLanguage;

  original: boolean;

  title: string;

  translator: string | null;

  description: string | null;

  publisher: string | null;

  publication_year: number | null;

  cover: string | null;

  summary_text: string | null;

  summary_contributor_id: string | null;

  shop_url: string | null;

  download_url: string | null;
}

/** Represents the initializer for the table content.books_localized */
export interface BooksLocalizedInitializer {
  book_id: ResourcesId;

  language: BooksLocalizedLanguage;

  original: boolean;

  title: string;

  translator?: string | null;

  description?: string | null;

  publisher?: string | null;

  publication_year?: number | null;

  cover?: string | null;

  summary_text?: string | null;

  summary_contributor_id?: string | null;

  shop_url?: string | null;

  download_url?: string | null;
}

/** Represents the mutator for the table content.books_localized */
export interface BooksLocalizedMutator {
  book_id?: ResourcesId;

  language?: BooksLocalizedLanguage;

  original?: boolean;

  title?: string;

  translator?: string | null;

  description?: string | null;

  publisher?: string | null;

  publication_year?: number | null;

  cover?: string | null;

  summary_text?: string | null;

  summary_contributor_id?: string | null;

  shop_url?: string | null;

  download_url?: string | null;
}
