// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources.js';

/** Identifier type for content.books_localized */
export type BooksLocalizedLanguage = string;

/** Represents the table content.books_localized */
export default interface BooksLocalized {
  book_id: ResourcesId;

  language: BooksLocalizedLanguage;

  original: boolean;

  title: string;

  translator?: string;

  description?: string;

  publisher?: string;

  publication_year?: number;

  cover?: string;

  summary_text?: string;

  summary_contributor_id?: string;

  shop_url?: string;

  download_url?: string;
}

/** Represents the initializer for the table content.books_localized */
export interface BooksLocalizedInitializer {
  book_id: ResourcesId;

  language: BooksLocalizedLanguage;

  original: boolean;

  title: string;

  translator?: string;

  description?: string;

  publisher?: string;

  publication_year?: number;

  cover?: string;

  summary_text?: string;

  summary_contributor_id?: string;

  shop_url?: string;

  download_url?: string;
}

/** Represents the mutator for the table content.books_localized */
export interface BooksLocalizedMutator {
  book_id?: ResourcesId;

  language?: BooksLocalizedLanguage;

  original?: boolean;

  title?: string;

  translator?: string;

  description?: string;

  publisher?: string;

  publication_year?: number;

  cover?: string;

  summary_text?: string;

  summary_contributor_id?: string;

  shop_url?: string;

  download_url?: string;
}
