// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources.js';

/** Represents the table content.builders */
export default interface Builders {
  resource_id: ResourcesId;

  name: string;

  category: string;

  website_url?: string;

  twitter_url?: string;

  github_url?: string;

  nostr?: string;
}

/** Represents the initializer for the table content.builders */
export interface BuildersInitializer {
  resource_id: ResourcesId;

  name: string;

  category: string;

  website_url?: string;

  twitter_url?: string;

  github_url?: string;

  nostr?: string;
}

/** Represents the mutator for the table content.builders */
export interface BuildersMutator {
  resource_id?: ResourcesId;

  name?: string;

  category?: string;

  website_url?: string;

  twitter_url?: string;

  github_url?: string;

  nostr?: string;
}
