// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources.js';

/** Identifier type for content.builders_localized */
export type BuildersLocalizedLanguage = string;

/** Represents the table content.builders_localized */
export default interface BuildersLocalized {
  builder_id: ResourcesId;

  language: BuildersLocalizedLanguage;

  description?: string;
}

/** Represents the initializer for the table content.builders_localized */
export interface BuildersLocalizedInitializer {
  builder_id: ResourcesId;

  language: BuildersLocalizedLanguage;

  description?: string;
}

/** Represents the mutator for the table content.builders_localized */
export interface BuildersLocalizedMutator {
  builder_id?: ResourcesId;

  language?: BuildersLocalizedLanguage;

  description?: string;
}
