// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CoursesId } from './Courses';

/** Identifier type for content.course_chapters_localized */
export type CourseChaptersLocalizedLanguage = string;

/** Identifier type for content.course_chapters_localized */
export type CourseChaptersLocalizedChapter = number;

/** Represents the table content.course_chapters_localized */
export default interface CourseChaptersLocalized {
  course_id: CoursesId;

  language: CourseChaptersLocalizedLanguage;

  chapter: CourseChaptersLocalizedChapter;

  title: string;

  raw_content: string;
}

/** Represents the initializer for the table content.course_chapters_localized */
export interface CourseChaptersLocalizedInitializer {
  course_id: CoursesId;

  language: CourseChaptersLocalizedLanguage;

  chapter: CourseChaptersLocalizedChapter;

  title: string;

  raw_content: string;
}

/** Represents the mutator for the table content.course_chapters_localized */
export interface CourseChaptersLocalizedMutator {
  course_id?: CoursesId;

  language?: CourseChaptersLocalizedLanguage;

  chapter?: CourseChaptersLocalizedChapter;

  title?: string;

  raw_content?: string;
}
