// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CoursesId } from './Courses.js';
import type { TagsId } from './Tags.js';

/** Represents the table content.course_tags */
export default interface CourseTags {
  course_id: CoursesId;

  tag_id: TagsId;
}

/** Represents the initializer for the table content.course_tags */
export interface CourseTagsInitializer {
  course_id: CoursesId;

  tag_id: TagsId;
}

/** Represents the mutator for the table content.course_tags */
export interface CourseTagsMutator {
  course_id?: CoursesId;

  tag_id?: TagsId;
}
