// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CoursesId } from './Courses.js';

/** Identifier type for content.courses_localized */
export type CoursesLocalizedLanguage = string;

/** Represents the table content.courses_localized */
export default interface CoursesLocalized {
  course_id: CoursesId;

  language: CoursesLocalizedLanguage;

  name: string;

  goal: string;

  objectives: string[];

  raw_description: string;
}

/** Represents the initializer for the table content.courses_localized */
export interface CoursesLocalizedInitializer {
  course_id: CoursesId;

  language: CoursesLocalizedLanguage;

  name: string;

  goal: string;

  objectives: string[];

  raw_description: string;
}

/** Represents the mutator for the table content.courses_localized */
export interface CoursesLocalizedMutator {
  course_id?: CoursesId;

  language?: CoursesLocalizedLanguage;

  name?: string;

  goal?: string;

  objectives?: string[];

  raw_description?: string;
}
