// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CoursesId } from './Courses.js';
import type { CoursePartsPart } from './CourseParts.js';
import type { CourseChaptersChapter } from './CourseChapters.js';
import type { CoursesLocalizedLanguage } from './CoursesLocalized.js';

/** Represents the table content.course_chapters_localized */
export default interface CourseChaptersLocalized {
  course_id: CoursesId | CoursesId | CoursesId | CoursesId;

  part: CoursePartsPart | CoursePartsPart;

  chapter: CourseChaptersChapter;

  language: CoursesLocalizedLanguage | CoursesLocalizedLanguage;

  title: string;

  sections: string[];

  raw_content: string;
}

/** Represents the initializer for the table content.course_chapters_localized */
export interface CourseChaptersLocalizedInitializer {
  course_id: CoursesId | CoursesId | CoursesId | CoursesId;

  part: CoursePartsPart | CoursePartsPart;

  chapter: CourseChaptersChapter;

  language: CoursesLocalizedLanguage | CoursesLocalizedLanguage;

  title: string;

  sections: string[];

  raw_content: string;
}

/** Represents the mutator for the table content.course_chapters_localized */
export interface CourseChaptersLocalizedMutator {
  course_id?: CoursesId | CoursesId | CoursesId | CoursesId;

  part?: CoursePartsPart | CoursePartsPart;

  chapter?: CourseChaptersChapter;

  language?: CoursesLocalizedLanguage | CoursesLocalizedLanguage;

  title?: string;

  sections?: string[];

  raw_content?: string;
}
