// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources';

/** Represents the table content.podcasts */
export default interface Podcasts {
  resource_id: ResourcesId;

  language: string;

  name: string;

  host: string;

  description: string | null;

  website_url: string | null;

  twitter_url: string | null;

  podcast_url: string | null;

  nostr: string | null;
}

/** Represents the initializer for the table content.podcasts */
export interface PodcastsInitializer {
  resource_id: ResourcesId;

  language: string;

  name: string;

  host: string;

  description?: string | null;

  website_url?: string | null;

  twitter_url?: string | null;

  podcast_url?: string | null;

  nostr?: string | null;
}

/** Represents the mutator for the table content.podcasts */
export interface PodcastsMutator {
  resource_id?: ResourcesId;

  language?: string;

  name?: string;

  host?: string;

  description?: string | null;

  website_url?: string | null;

  twitter_url?: string | null;

  podcast_url?: string | null;

  nostr?: string | null;
}
