// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources';

/** Identifier type for content.podcasts */
export type PodcastsId = number;

/** Represents the table content.podcasts */
export default interface Podcasts {
  id: PodcastsId;

  resource_id: ResourcesId;

  language: string;

  name: string;

  description: string | null;

  platform_url: string | null;
}

/** Represents the initializer for the table content.podcasts */
export interface PodcastsInitializer {
  /** Default value: nextval('content.podcasts_id_seq'::regclass) */
  id?: PodcastsId;

  resource_id: ResourcesId;

  language: string;

  name: string;

  description?: string | null;

  platform_url?: string | null;
}

/** Represents the mutator for the table content.podcasts */
export interface PodcastsMutator {
  id?: PodcastsId;

  resource_id?: ResourcesId;

  language?: string;

  name?: string;

  description?: string | null;

  platform_url?: string | null;
}
