// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProfessorsId } from './Professors.js';
import type { TagsId } from './Tags.js';

/** Represents the table content.professor_tags */
export default interface ProfessorTags {
  professor_id: ProfessorsId;

  tag_id: TagsId;
}

/** Represents the initializer for the table content.professor_tags */
export interface ProfessorTagsInitializer {
  professor_id: ProfessorsId;

  tag_id: TagsId;
}

/** Represents the mutator for the table content.professor_tags */
export interface ProfessorTagsMutator {
  professor_id?: ProfessorsId;

  tag_id?: TagsId;
}
