// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProfessorsId } from './Professors.js';

/** Identifier type for content.professors_localized */
export type ProfessorsLocalizedLanguage = string;

/** Represents the table content.professors_localized */
export default interface ProfessorsLocalized {
  professor_id: ProfessorsId;

  language: ProfessorsLocalizedLanguage;

  bio?: string;

  short_bio?: string;
}

/** Represents the initializer for the table content.professors_localized */
export interface ProfessorsLocalizedInitializer {
  professor_id: ProfessorsId;

  language: ProfessorsLocalizedLanguage;

  bio?: string;

  short_bio?: string;
}

/** Represents the mutator for the table content.professors_localized */
export interface ProfessorsLocalizedMutator {
  professor_id?: ProfessorsId;

  language?: ProfessorsLocalizedLanguage;

  bio?: string;

  short_bio?: string;
}
