// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for content.resources */
export type ResourcesId = number;

/** Represents the table content.resources */
export default interface Resources {
  id: ResourcesId;

  type: string;

  path: string;

  original_language: string;

  last_updated: number;

  last_commit: string;
}

/** Represents the initializer for the table content.resources */
export interface ResourcesInitializer {
  /** Default value: nextval('content.resources_id_seq'::regclass) */
  id?: ResourcesId;

  type: string;

  path: string;

  original_language: string;

  /** Default value: now() */
  last_updated?: number;

  last_commit: string;
}

/** Represents the mutator for the table content.resources */
export interface ResourcesMutator {
  id?: ResourcesId;

  type?: string;

  path?: string;

  original_language?: string;

  last_updated?: number;

  last_commit?: string;
}
