// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for content.resources */
export type ResourcesId = number;

/** Represents the table content.resources */
export default interface Resources {
  id: ResourcesId;

  category: string;

  path: string;

  last_updated: number;

  last_commit: string;

  last_sync: number;
}

/** Represents the initializer for the table content.resources */
export interface ResourcesInitializer {
  /** Default value: nextval('content.resources_id_seq'::regclass) */
  id?: ResourcesId;

  category: string;

  path: string;

  /** Default value: now() */
  last_updated?: number;

  last_commit: string;

  /** Default value: now() */
  last_sync?: number;
}

/** Represents the mutator for the table content.resources */
export interface ResourcesMutator {
  id?: ResourcesId;

  category?: string;

  path?: string;

  last_updated?: number;

  last_commit?: string;

  last_sync?: number;
}
