// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for content.tags */
export type TagsId = number;

/** Represents the table content.tags */
export default interface Tags {
  id: TagsId;

  tag_name: string;

  description: string | null;
}

/** Represents the initializer for the table content.tags */
export interface TagsInitializer {
  /** Default value: nextval('content.tags_id_seq'::regclass) */
  id?: TagsId;

  tag_name: string;

  description?: string | null;
}

/** Represents the mutator for the table content.tags */
export interface TagsMutator {
  id?: TagsId;

  tag_name?: string;

  description?: string | null;
}
