// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for content.tutorials */
export type TutorialsId = number;

/** Represents the table content.tutorials */
export default interface Tutorials {
  id: TutorialsId;

  path: string;

  level: string;

  builder?: string;

  last_updated: number;

  last_commit: string;
}

/** Represents the initializer for the table content.tutorials */
export interface TutorialsInitializer {
  /** Default value: nextval('content.tutorials_id_seq'::regclass) */
  id?: TutorialsId;

  path: string;

  level: string;

  builder?: string;

  /** Default value: now() */
  last_updated?: number;

  last_commit: string;
}

/** Represents the mutator for the table content.tutorials */
export interface TutorialsMutator {
  id?: TutorialsId;

  path?: string;

  level?: string;

  builder?: string;

  last_updated?: number;

  last_commit?: string;
}
