/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as DashboardDashboardImport } from './routes/dashboard/_dashboard';
import { Route as ContentTutorialsIndexImport } from './routes/_content/tutorials/index';
import { Route as ContentResourcesIndexImport } from './routes/_content/resources/index';
import { Route as ContentEventsIndexImport } from './routes/_content/events/index';
import { Route as ContentCoursesIndexImport } from './routes/_content/courses/index';
import { Route as DashboardDashboardProfileImport } from './routes/dashboard/_dashboard/profile';
import { Route as DashboardDashboardCredentialsImport } from './routes/dashboard/_dashboard/credentials';
import { Route as DashboardDashboardCoursesImport } from './routes/dashboard/_dashboard/courses';
import { Route as DashboardDashboardCalendarImport } from './routes/dashboard/_dashboard/calendar';
import { Route as DashboardDashboardBookingsImport } from './routes/dashboard/_dashboard/bookings';
import { Route as ContentEventsEventIdImport } from './routes/_content/events/$eventId';
import { Route as ContentMiscUnderConstructionImport } from './routes/_content/_misc/under-construction';
import { Route as ContentMiscTermsAndConditionsImport } from './routes/_content/_misc/terms-and-conditions';
import { Route as ContentMiscNodeNetworkImport } from './routes/_content/_misc/node-network';
import { Route as ContentMiscManifestoImport } from './routes/_content/_misc/manifesto';
import { Route as ContentMiscBCertificateImport } from './routes/_content/_misc/b-certificate';
import { Route as ContentMiscAboutImport } from './routes/_content/_misc/about';
import { Route as ContentTutorialsCategoryIndexImport } from './routes/_content/tutorials/$category/index';
import { Route as ContentResourcesPodcastsIndexImport } from './routes/_content/resources/podcasts/index';
import { Route as ContentResourcesNewslettersIndexImport } from './routes/_content/resources/newsletters/index';
import { Route as ContentResourcesGlossaryIndexImport } from './routes/_content/resources/glossary/index';
import { Route as ContentResourcesConferencesIndexImport } from './routes/_content/resources/conferences/index';
import { Route as ContentResourcesBuildersIndexImport } from './routes/_content/resources/builders/index';
import { Route as ContentResourcesBooksIndexImport } from './routes/_content/resources/books/index';
import { Route as ContentResourcesBetIndexImport } from './routes/_content/resources/bet/index';
import { Route as ContentCoursesCourseIdIndexImport } from './routes/_content/courses/$courseId/index';
import { Route as ContentMiscPublicCommunicationIndexImport } from './routes/_content/_misc/public-communication/index';
import { Route as ContentMiscProfessorsIndexImport } from './routes/_content/_misc/professors/index';
import { Route as DashboardDashboardProfessorTutorialsImport } from './routes/dashboard/_dashboard/professor/tutorials';
import { Route as DashboardDashboardProfessorProfileImport } from './routes/dashboard/_dashboard/professor/profile';
import { Route as DashboardDashboardProfessorCoursesImport } from './routes/dashboard/_dashboard/professor/courses';
import { Route as DashboardDashboardCourseCompletedImport } from './routes/dashboard/_dashboard/course/completed';
import { Route as DashboardDashboardCourseCourseIdImport } from './routes/dashboard/_dashboard/course/$courseId';
import { Route as DashboardDashboardAdministrationTutorialsImport } from './routes/dashboard/_dashboard/administration/tutorials';
import { Route as DashboardDashboardAdministrationRoleImport } from './routes/dashboard/_dashboard/administration/role';
import { Route as DashboardDashboardAdministrationBookingsImport } from './routes/dashboard/_dashboard/administration/bookings';
import { Route as ContentResourcesPodcastsPodcastNamePodcastIdImport } from './routes/_content/resources/podcasts/$podcastName-$podcastId';
import { Route as ContentResourcesNewslettersNewsletterNameNewsletterIdImport } from './routes/_content/resources/newsletters/$newsletterName-$newsletterId';
import { Route as ContentResourcesGlossaryWordIdImport } from './routes/_content/resources/glossary/$wordId';
import { Route as ContentResourcesConferencesConferenceNameConferenceIdImport } from './routes/_content/resources/conferences/$conferenceName-$conferenceId';
import { Route as ContentResourcesBuildersBuilderNameBuilderIdImport } from './routes/_content/resources/builders/$builderName-$builderId';
import { Route as ContentResourcesBooksBookNameBookIdImport } from './routes/_content/resources/books/$bookName-$bookId';
import { Route as ContentCoursesCourseIdChapterIdImport } from './routes/_content/courses/$courseId/$chapterId';
import { Route as ContentMiscValidateEmailTokenImport } from './routes/_content/_misc/validate-email.$token';
import { Route as ContentMiscResetPasswordTokenImport } from './routes/_content/_misc/reset-password.$token';
import { Route as ContentMiscPublicCommunicationLegalsImport } from './routes/_content/_misc/public-communication/legals';
import { Route as ContentMiscProfessorProfessorNameProfessorIdImport } from './routes/_content/_misc/professor.$professorName-$professorId';
import { Route as ContentMiscExamCertificatesCertificateIdImport } from './routes/_content/_misc/exam-certificates.$certificateId';
import { Route as ContentMiscBcertCertificatesCertificateIdImport } from './routes/_content/_misc/bcert-certificates.$certificateId';
import { Route as ContentMiscPublicCommunicationLegalsIndexImport } from './routes/_content/_misc/public-communication/legals/index';
import { Route as ContentMiscPublicCommunicationBlogsAndNewsIndexImport } from './routes/_content/_misc/public-communication/blogs-and-news/index';
import { Route as ContentMiscProfessorsCategoryIndexImport } from './routes/_content/_misc/professors/$category/index';
import { Route as ContentTutorialsCategorySubcategoryNameIdImport } from './routes/_content/tutorials/$category/$subcategory.$name-$id';
import { Route as ContentMiscPublicCommunicationLegalsNameImport } from './routes/_content/_misc/public-communication/legals/$name';
import { Route as ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexImport } from './routes/_content/_misc/public-communication/blogs-and-news/$category/index';
import { Route as ContentMiscPublicCommunicationBlogsAndNewsCategoryNameImport } from './routes/_content/_misc/public-communication/blogs-and-news/$category/$name';

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')();

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const DashboardDashboardRoute = DashboardDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => DashboardRoute,
} as any);

const ContentTutorialsIndexRoute = ContentTutorialsIndexImport.update({
  id: '/_content/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => rootRoute,
} as any);

const ContentResourcesIndexRoute = ContentResourcesIndexImport.update({
  id: '/_content/resources/',
  path: '/resources/',
  getParentRoute: () => rootRoute,
} as any);

const ContentEventsIndexRoute = ContentEventsIndexImport.update({
  id: '/_content/events/',
  path: '/events/',
  getParentRoute: () => rootRoute,
} as any);

const ContentCoursesIndexRoute = ContentCoursesIndexImport.update({
  id: '/_content/courses/',
  path: '/courses/',
  getParentRoute: () => rootRoute,
} as any);

const DashboardDashboardProfileRoute = DashboardDashboardProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardDashboardRoute,
} as any);

const DashboardDashboardCredentialsRoute =
  DashboardDashboardCredentialsImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => DashboardDashboardRoute,
  } as any);

const DashboardDashboardCoursesRoute = DashboardDashboardCoursesImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardDashboardRoute,
} as any);

const DashboardDashboardCalendarRoute = DashboardDashboardCalendarImport.update(
  {
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => DashboardDashboardRoute,
  } as any,
);

const DashboardDashboardBookingsRoute = DashboardDashboardBookingsImport.update(
  {
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any,
);

const ContentEventsEventIdRoute = ContentEventsEventIdImport.update({
  id: '/_content/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRoute,
} as any);

const ContentMiscUnderConstructionRoute =
  ContentMiscUnderConstructionImport.update({
    id: '/_content/_misc/under-construction',
    path: '/under-construction',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscTermsAndConditionsRoute =
  ContentMiscTermsAndConditionsImport.update({
    id: '/_content/_misc/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscNodeNetworkRoute = ContentMiscNodeNetworkImport.update({
  id: '/_content/_misc/node-network',
  path: '/node-network',
  getParentRoute: () => rootRoute,
} as any);

const ContentMiscManifestoRoute = ContentMiscManifestoImport.update({
  id: '/_content/_misc/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRoute,
} as any);

const ContentMiscBCertificateRoute = ContentMiscBCertificateImport.update({
  id: '/_content/_misc/b-certificate',
  path: '/b-certificate',
  getParentRoute: () => rootRoute,
} as any);

const ContentMiscAboutRoute = ContentMiscAboutImport.update({
  id: '/_content/_misc/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any);

const ContentTutorialsCategoryIndexRoute =
  ContentTutorialsCategoryIndexImport.update({
    id: '/_content/tutorials/$category/',
    path: '/tutorials/$category/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesPodcastsIndexRoute =
  ContentResourcesPodcastsIndexImport.update({
    id: '/_content/resources/podcasts/',
    path: '/resources/podcasts/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesNewslettersIndexRoute =
  ContentResourcesNewslettersIndexImport.update({
    id: '/_content/resources/newsletters/',
    path: '/resources/newsletters/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesGlossaryIndexRoute =
  ContentResourcesGlossaryIndexImport.update({
    id: '/_content/resources/glossary/',
    path: '/resources/glossary/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesConferencesIndexRoute =
  ContentResourcesConferencesIndexImport.update({
    id: '/_content/resources/conferences/',
    path: '/resources/conferences/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesBuildersIndexRoute =
  ContentResourcesBuildersIndexImport.update({
    id: '/_content/resources/builders/',
    path: '/resources/builders/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesBooksIndexRoute = ContentResourcesBooksIndexImport.update(
  {
    id: '/_content/resources/books/',
    path: '/resources/books/',
    getParentRoute: () => rootRoute,
  } as any,
);

const ContentResourcesBetIndexRoute = ContentResourcesBetIndexImport.update({
  id: '/_content/resources/bet/',
  path: '/resources/bet/',
  getParentRoute: () => rootRoute,
} as any);

const ContentCoursesCourseIdIndexRoute =
  ContentCoursesCourseIdIndexImport.update({
    id: '/_content/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscPublicCommunicationIndexRoute =
  ContentMiscPublicCommunicationIndexImport.update({
    id: '/_content/_misc/public-communication/',
    path: '/public-communication/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscProfessorsIndexRoute = ContentMiscProfessorsIndexImport.update(
  {
    id: '/_content/_misc/professors/',
    path: '/professors/',
    getParentRoute: () => rootRoute,
  } as any,
);

const DashboardDashboardProfessorTutorialsRoute =
  DashboardDashboardProfessorTutorialsImport.update({
    id: '/professor/tutorials',
    path: '/professor/tutorials',
    getParentRoute: () => DashboardDashboardRoute,
  } as any);

const DashboardDashboardProfessorProfileRoute =
  DashboardDashboardProfessorProfileImport.update({
    id: '/professor/profile',
    path: '/professor/profile',
    getParentRoute: () => DashboardDashboardRoute,
  } as any);

const DashboardDashboardProfessorCoursesRoute =
  DashboardDashboardProfessorCoursesImport.update({
    id: '/professor/courses',
    path: '/professor/courses',
    getParentRoute: () => DashboardDashboardRoute,
  } as any);

const DashboardDashboardCourseCompletedRoute =
  DashboardDashboardCourseCompletedImport.update({
    id: '/course/completed',
    path: '/course/completed',
    getParentRoute: () => DashboardDashboardRoute,
  } as any);

const DashboardDashboardCourseCourseIdRoute =
  DashboardDashboardCourseCourseIdImport.update({
    id: '/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => DashboardDashboardRoute,
  } as any);

const DashboardDashboardAdministrationTutorialsRoute =
  DashboardDashboardAdministrationTutorialsImport.update({
    id: '/administration/tutorials',
    path: '/administration/tutorials',
    getParentRoute: () => DashboardDashboardRoute,
  } as any);

const DashboardDashboardAdministrationRoleRoute =
  DashboardDashboardAdministrationRoleImport.update({
    id: '/administration/role',
    path: '/administration/role',
    getParentRoute: () => DashboardDashboardRoute,
  } as any);

const DashboardDashboardAdministrationBookingsRoute =
  DashboardDashboardAdministrationBookingsImport.update({
    id: '/administration/bookings',
    path: '/administration/bookings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any);

const ContentResourcesPodcastsPodcastNamePodcastIdRoute =
  ContentResourcesPodcastsPodcastNamePodcastIdImport.update({
    id: '/_content/resources/podcasts/$podcastName-$podcastId',
    path: '/resources/podcasts/$podcastName-$podcastId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesNewslettersNewsletterNameNewsletterIdRoute =
  ContentResourcesNewslettersNewsletterNameNewsletterIdImport.update({
    id: '/_content/resources/newsletters/$newsletterName-$newsletterId',
    path: '/resources/newsletters/$newsletterName-$newsletterId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesGlossaryWordIdRoute =
  ContentResourcesGlossaryWordIdImport.update({
    id: '/_content/resources/glossary/$wordId',
    path: '/resources/glossary/$wordId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesConferencesConferenceNameConferenceIdRoute =
  ContentResourcesConferencesConferenceNameConferenceIdImport.update({
    id: '/_content/resources/conferences/$conferenceName-$conferenceId',
    path: '/resources/conferences/$conferenceName-$conferenceId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesBuildersBuilderNameBuilderIdRoute =
  ContentResourcesBuildersBuilderNameBuilderIdImport.update({
    id: '/_content/resources/builders/$builderName-$builderId',
    path: '/resources/builders/$builderName-$builderId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentResourcesBooksBookNameBookIdRoute =
  ContentResourcesBooksBookNameBookIdImport.update({
    id: '/_content/resources/books/$bookName-$bookId',
    path: '/resources/books/$bookName-$bookId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentCoursesCourseIdChapterIdRoute =
  ContentCoursesCourseIdChapterIdImport.update({
    id: '/_content/courses/$courseId/$chapterId',
    path: '/courses/$courseId/$chapterId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscValidateEmailTokenRoute =
  ContentMiscValidateEmailTokenImport.update({
    id: '/_content/_misc/validate-email/$token',
    path: '/validate-email/$token',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscResetPasswordTokenRoute =
  ContentMiscResetPasswordTokenImport.update({
    id: '/_content/_misc/reset-password/$token',
    path: '/reset-password/$token',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscPublicCommunicationLegalsRoute =
  ContentMiscPublicCommunicationLegalsImport.update({
    id: '/_content/_misc/public-communication/legals',
    path: '/public-communication/legals',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscProfessorProfessorNameProfessorIdRoute =
  ContentMiscProfessorProfessorNameProfessorIdImport.update({
    id: '/_content/_misc/professor/$professorName-$professorId',
    path: '/professor/$professorName-$professorId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscExamCertificatesCertificateIdRoute =
  ContentMiscExamCertificatesCertificateIdImport.update({
    id: '/_content/_misc/exam-certificates/$certificateId',
    path: '/exam-certificates/$certificateId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscBcertCertificatesCertificateIdRoute =
  ContentMiscBcertCertificatesCertificateIdImport.update({
    id: '/_content/_misc/bcert-certificates/$certificateId',
    path: '/bcert-certificates/$certificateId',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscPublicCommunicationLegalsIndexRoute =
  ContentMiscPublicCommunicationLegalsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ContentMiscPublicCommunicationLegalsRoute,
  } as any);

const ContentMiscPublicCommunicationBlogsAndNewsIndexRoute =
  ContentMiscPublicCommunicationBlogsAndNewsIndexImport.update({
    id: '/_content/_misc/public-communication/blogs-and-news/',
    path: '/public-communication/blogs-and-news/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscProfessorsCategoryIndexRoute =
  ContentMiscProfessorsCategoryIndexImport.update({
    id: '/_content/_misc/professors/$category/',
    path: '/professors/$category/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentTutorialsCategorySubcategoryNameIdRoute =
  ContentTutorialsCategorySubcategoryNameIdImport.update({
    id: '/_content/tutorials/$category/$subcategory/$name-$id',
    path: '/tutorials/$category/$subcategory/$name-$id',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscPublicCommunicationLegalsNameRoute =
  ContentMiscPublicCommunicationLegalsNameImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => ContentMiscPublicCommunicationLegalsRoute,
  } as any);

const ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexRoute =
  ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexImport.update({
    id: '/_content/_misc/public-communication/blogs-and-news/$category/',
    path: '/public-communication/blogs-and-news/$category/',
    getParentRoute: () => rootRoute,
  } as any);

const ContentMiscPublicCommunicationBlogsAndNewsCategoryNameRoute =
  ContentMiscPublicCommunicationBlogsAndNewsCategoryNameImport.update({
    id: '/_content/_misc/public-communication/blogs-and-news/$category/$name',
    path: '/public-communication/blogs-and-news/$category/$name',
    getParentRoute: () => rootRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard/_dashboard': {
      id: '/dashboard/_dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardDashboardImport;
      parentRoute: typeof DashboardRoute;
    };
    '/_content/_misc/about': {
      id: '/_content/_misc/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof ContentMiscAboutImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/b-certificate': {
      id: '/_content/_misc/b-certificate';
      path: '/b-certificate';
      fullPath: '/b-certificate';
      preLoaderRoute: typeof ContentMiscBCertificateImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/manifesto': {
      id: '/_content/_misc/manifesto';
      path: '/manifesto';
      fullPath: '/manifesto';
      preLoaderRoute: typeof ContentMiscManifestoImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/node-network': {
      id: '/_content/_misc/node-network';
      path: '/node-network';
      fullPath: '/node-network';
      preLoaderRoute: typeof ContentMiscNodeNetworkImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/terms-and-conditions': {
      id: '/_content/_misc/terms-and-conditions';
      path: '/terms-and-conditions';
      fullPath: '/terms-and-conditions';
      preLoaderRoute: typeof ContentMiscTermsAndConditionsImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/under-construction': {
      id: '/_content/_misc/under-construction';
      path: '/under-construction';
      fullPath: '/under-construction';
      preLoaderRoute: typeof ContentMiscUnderConstructionImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/events/$eventId': {
      id: '/_content/events/$eventId';
      path: '/events/$eventId';
      fullPath: '/events/$eventId';
      preLoaderRoute: typeof ContentEventsEventIdImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard/_dashboard/bookings': {
      id: '/dashboard/_dashboard/bookings';
      path: '/bookings';
      fullPath: '/dashboard/bookings';
      preLoaderRoute: typeof DashboardDashboardBookingsImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/calendar': {
      id: '/dashboard/_dashboard/calendar';
      path: '/calendar';
      fullPath: '/dashboard/calendar';
      preLoaderRoute: typeof DashboardDashboardCalendarImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/courses': {
      id: '/dashboard/_dashboard/courses';
      path: '/courses';
      fullPath: '/dashboard/courses';
      preLoaderRoute: typeof DashboardDashboardCoursesImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/credentials': {
      id: '/dashboard/_dashboard/credentials';
      path: '/credentials';
      fullPath: '/dashboard/credentials';
      preLoaderRoute: typeof DashboardDashboardCredentialsImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/profile': {
      id: '/dashboard/_dashboard/profile';
      path: '/profile';
      fullPath: '/dashboard/profile';
      preLoaderRoute: typeof DashboardDashboardProfileImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/_content/courses/': {
      id: '/_content/courses/';
      path: '/courses';
      fullPath: '/courses';
      preLoaderRoute: typeof ContentCoursesIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/events/': {
      id: '/_content/events/';
      path: '/events';
      fullPath: '/events';
      preLoaderRoute: typeof ContentEventsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/': {
      id: '/_content/resources/';
      path: '/resources';
      fullPath: '/resources';
      preLoaderRoute: typeof ContentResourcesIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/tutorials/': {
      id: '/_content/tutorials/';
      path: '/tutorials';
      fullPath: '/tutorials';
      preLoaderRoute: typeof ContentTutorialsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/bcert-certificates/$certificateId': {
      id: '/_content/_misc/bcert-certificates/$certificateId';
      path: '/bcert-certificates/$certificateId';
      fullPath: '/bcert-certificates/$certificateId';
      preLoaderRoute: typeof ContentMiscBcertCertificatesCertificateIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/exam-certificates/$certificateId': {
      id: '/_content/_misc/exam-certificates/$certificateId';
      path: '/exam-certificates/$certificateId';
      fullPath: '/exam-certificates/$certificateId';
      preLoaderRoute: typeof ContentMiscExamCertificatesCertificateIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/professor/$professorName-$professorId': {
      id: '/_content/_misc/professor/$professorName-$professorId';
      path: '/professor/$professorName-$professorId';
      fullPath: '/professor/$professorName-$professorId';
      preLoaderRoute: typeof ContentMiscProfessorProfessorNameProfessorIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/public-communication/legals': {
      id: '/_content/_misc/public-communication/legals';
      path: '/public-communication/legals';
      fullPath: '/public-communication/legals';
      preLoaderRoute: typeof ContentMiscPublicCommunicationLegalsImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/reset-password/$token': {
      id: '/_content/_misc/reset-password/$token';
      path: '/reset-password/$token';
      fullPath: '/reset-password/$token';
      preLoaderRoute: typeof ContentMiscResetPasswordTokenImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/validate-email/$token': {
      id: '/_content/_misc/validate-email/$token';
      path: '/validate-email/$token';
      fullPath: '/validate-email/$token';
      preLoaderRoute: typeof ContentMiscValidateEmailTokenImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/courses/$courseId/$chapterId': {
      id: '/_content/courses/$courseId/$chapterId';
      path: '/courses/$courseId/$chapterId';
      fullPath: '/courses/$courseId/$chapterId';
      preLoaderRoute: typeof ContentCoursesCourseIdChapterIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/books/$bookName-$bookId': {
      id: '/_content/resources/books/$bookName-$bookId';
      path: '/resources/books/$bookName-$bookId';
      fullPath: '/resources/books/$bookName-$bookId';
      preLoaderRoute: typeof ContentResourcesBooksBookNameBookIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/builders/$builderName-$builderId': {
      id: '/_content/resources/builders/$builderName-$builderId';
      path: '/resources/builders/$builderName-$builderId';
      fullPath: '/resources/builders/$builderName-$builderId';
      preLoaderRoute: typeof ContentResourcesBuildersBuilderNameBuilderIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/conferences/$conferenceName-$conferenceId': {
      id: '/_content/resources/conferences/$conferenceName-$conferenceId';
      path: '/resources/conferences/$conferenceName-$conferenceId';
      fullPath: '/resources/conferences/$conferenceName-$conferenceId';
      preLoaderRoute: typeof ContentResourcesConferencesConferenceNameConferenceIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/glossary/$wordId': {
      id: '/_content/resources/glossary/$wordId';
      path: '/resources/glossary/$wordId';
      fullPath: '/resources/glossary/$wordId';
      preLoaderRoute: typeof ContentResourcesGlossaryWordIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/newsletters/$newsletterName-$newsletterId': {
      id: '/_content/resources/newsletters/$newsletterName-$newsletterId';
      path: '/resources/newsletters/$newsletterName-$newsletterId';
      fullPath: '/resources/newsletters/$newsletterName-$newsletterId';
      preLoaderRoute: typeof ContentResourcesNewslettersNewsletterNameNewsletterIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/podcasts/$podcastName-$podcastId': {
      id: '/_content/resources/podcasts/$podcastName-$podcastId';
      path: '/resources/podcasts/$podcastName-$podcastId';
      fullPath: '/resources/podcasts/$podcastName-$podcastId';
      preLoaderRoute: typeof ContentResourcesPodcastsPodcastNamePodcastIdImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard/_dashboard/administration/bookings': {
      id: '/dashboard/_dashboard/administration/bookings';
      path: '/administration/bookings';
      fullPath: '/dashboard/administration/bookings';
      preLoaderRoute: typeof DashboardDashboardAdministrationBookingsImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/administration/role': {
      id: '/dashboard/_dashboard/administration/role';
      path: '/administration/role';
      fullPath: '/dashboard/administration/role';
      preLoaderRoute: typeof DashboardDashboardAdministrationRoleImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/administration/tutorials': {
      id: '/dashboard/_dashboard/administration/tutorials';
      path: '/administration/tutorials';
      fullPath: '/dashboard/administration/tutorials';
      preLoaderRoute: typeof DashboardDashboardAdministrationTutorialsImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/course/$courseId': {
      id: '/dashboard/_dashboard/course/$courseId';
      path: '/course/$courseId';
      fullPath: '/dashboard/course/$courseId';
      preLoaderRoute: typeof DashboardDashboardCourseCourseIdImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/course/completed': {
      id: '/dashboard/_dashboard/course/completed';
      path: '/course/completed';
      fullPath: '/dashboard/course/completed';
      preLoaderRoute: typeof DashboardDashboardCourseCompletedImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/professor/courses': {
      id: '/dashboard/_dashboard/professor/courses';
      path: '/professor/courses';
      fullPath: '/dashboard/professor/courses';
      preLoaderRoute: typeof DashboardDashboardProfessorCoursesImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/professor/profile': {
      id: '/dashboard/_dashboard/professor/profile';
      path: '/professor/profile';
      fullPath: '/dashboard/professor/profile';
      preLoaderRoute: typeof DashboardDashboardProfessorProfileImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/dashboard/_dashboard/professor/tutorials': {
      id: '/dashboard/_dashboard/professor/tutorials';
      path: '/professor/tutorials';
      fullPath: '/dashboard/professor/tutorials';
      preLoaderRoute: typeof DashboardDashboardProfessorTutorialsImport;
      parentRoute: typeof DashboardDashboardImport;
    };
    '/_content/_misc/professors/': {
      id: '/_content/_misc/professors/';
      path: '/professors';
      fullPath: '/professors';
      preLoaderRoute: typeof ContentMiscProfessorsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/public-communication/': {
      id: '/_content/_misc/public-communication/';
      path: '/public-communication';
      fullPath: '/public-communication';
      preLoaderRoute: typeof ContentMiscPublicCommunicationIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/courses/$courseId/': {
      id: '/_content/courses/$courseId/';
      path: '/courses/$courseId';
      fullPath: '/courses/$courseId';
      preLoaderRoute: typeof ContentCoursesCourseIdIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/bet/': {
      id: '/_content/resources/bet/';
      path: '/resources/bet';
      fullPath: '/resources/bet';
      preLoaderRoute: typeof ContentResourcesBetIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/books/': {
      id: '/_content/resources/books/';
      path: '/resources/books';
      fullPath: '/resources/books';
      preLoaderRoute: typeof ContentResourcesBooksIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/builders/': {
      id: '/_content/resources/builders/';
      path: '/resources/builders';
      fullPath: '/resources/builders';
      preLoaderRoute: typeof ContentResourcesBuildersIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/conferences/': {
      id: '/_content/resources/conferences/';
      path: '/resources/conferences';
      fullPath: '/resources/conferences';
      preLoaderRoute: typeof ContentResourcesConferencesIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/glossary/': {
      id: '/_content/resources/glossary/';
      path: '/resources/glossary';
      fullPath: '/resources/glossary';
      preLoaderRoute: typeof ContentResourcesGlossaryIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/newsletters/': {
      id: '/_content/resources/newsletters/';
      path: '/resources/newsletters';
      fullPath: '/resources/newsletters';
      preLoaderRoute: typeof ContentResourcesNewslettersIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/resources/podcasts/': {
      id: '/_content/resources/podcasts/';
      path: '/resources/podcasts';
      fullPath: '/resources/podcasts';
      preLoaderRoute: typeof ContentResourcesPodcastsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/tutorials/$category/': {
      id: '/_content/tutorials/$category/';
      path: '/tutorials/$category';
      fullPath: '/tutorials/$category';
      preLoaderRoute: typeof ContentTutorialsCategoryIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/public-communication/legals/$name': {
      id: '/_content/_misc/public-communication/legals/$name';
      path: '/$name';
      fullPath: '/public-communication/legals/$name';
      preLoaderRoute: typeof ContentMiscPublicCommunicationLegalsNameImport;
      parentRoute: typeof ContentMiscPublicCommunicationLegalsImport;
    };
    '/_content/tutorials/$category/$subcategory/$name-$id': {
      id: '/_content/tutorials/$category/$subcategory/$name-$id';
      path: '/tutorials/$category/$subcategory/$name-$id';
      fullPath: '/tutorials/$category/$subcategory/$name-$id';
      preLoaderRoute: typeof ContentTutorialsCategorySubcategoryNameIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/professors/$category/': {
      id: '/_content/_misc/professors/$category/';
      path: '/professors/$category';
      fullPath: '/professors/$category';
      preLoaderRoute: typeof ContentMiscProfessorsCategoryIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/public-communication/blogs-and-news/': {
      id: '/_content/_misc/public-communication/blogs-and-news/';
      path: '/public-communication/blogs-and-news';
      fullPath: '/public-communication/blogs-and-news';
      preLoaderRoute: typeof ContentMiscPublicCommunicationBlogsAndNewsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/public-communication/legals/': {
      id: '/_content/_misc/public-communication/legals/';
      path: '/';
      fullPath: '/public-communication/legals/';
      preLoaderRoute: typeof ContentMiscPublicCommunicationLegalsIndexImport;
      parentRoute: typeof ContentMiscPublicCommunicationLegalsImport;
    };
    '/_content/_misc/public-communication/blogs-and-news/$category/$name': {
      id: '/_content/_misc/public-communication/blogs-and-news/$category/$name';
      path: '/public-communication/blogs-and-news/$category/$name';
      fullPath: '/public-communication/blogs-and-news/$category/$name';
      preLoaderRoute: typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryNameImport;
      parentRoute: typeof rootRoute;
    };
    '/_content/_misc/public-communication/blogs-and-news/$category/': {
      id: '/_content/_misc/public-communication/blogs-and-news/$category/';
      path: '/public-communication/blogs-and-news/$category';
      fullPath: '/public-communication/blogs-and-news/$category';
      preLoaderRoute: typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

interface DashboardDashboardRouteChildren {
  DashboardDashboardBookingsRoute: typeof DashboardDashboardBookingsRoute;
  DashboardDashboardCalendarRoute: typeof DashboardDashboardCalendarRoute;
  DashboardDashboardCoursesRoute: typeof DashboardDashboardCoursesRoute;
  DashboardDashboardCredentialsRoute: typeof DashboardDashboardCredentialsRoute;
  DashboardDashboardProfileRoute: typeof DashboardDashboardProfileRoute;
  DashboardDashboardAdministrationBookingsRoute: typeof DashboardDashboardAdministrationBookingsRoute;
  DashboardDashboardAdministrationRoleRoute: typeof DashboardDashboardAdministrationRoleRoute;
  DashboardDashboardAdministrationTutorialsRoute: typeof DashboardDashboardAdministrationTutorialsRoute;
  DashboardDashboardCourseCourseIdRoute: typeof DashboardDashboardCourseCourseIdRoute;
  DashboardDashboardCourseCompletedRoute: typeof DashboardDashboardCourseCompletedRoute;
  DashboardDashboardProfessorCoursesRoute: typeof DashboardDashboardProfessorCoursesRoute;
  DashboardDashboardProfessorProfileRoute: typeof DashboardDashboardProfessorProfileRoute;
  DashboardDashboardProfessorTutorialsRoute: typeof DashboardDashboardProfessorTutorialsRoute;
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardBookingsRoute: DashboardDashboardBookingsRoute,
  DashboardDashboardCalendarRoute: DashboardDashboardCalendarRoute,
  DashboardDashboardCoursesRoute: DashboardDashboardCoursesRoute,
  DashboardDashboardCredentialsRoute: DashboardDashboardCredentialsRoute,
  DashboardDashboardProfileRoute: DashboardDashboardProfileRoute,
  DashboardDashboardAdministrationBookingsRoute:
    DashboardDashboardAdministrationBookingsRoute,
  DashboardDashboardAdministrationRoleRoute:
    DashboardDashboardAdministrationRoleRoute,
  DashboardDashboardAdministrationTutorialsRoute:
    DashboardDashboardAdministrationTutorialsRoute,
  DashboardDashboardCourseCourseIdRoute: DashboardDashboardCourseCourseIdRoute,
  DashboardDashboardCourseCompletedRoute:
    DashboardDashboardCourseCompletedRoute,
  DashboardDashboardProfessorCoursesRoute:
    DashboardDashboardProfessorCoursesRoute,
  DashboardDashboardProfessorProfileRoute:
    DashboardDashboardProfessorProfileRoute,
  DashboardDashboardProfessorTutorialsRoute:
    DashboardDashboardProfessorTutorialsRoute,
};

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren);

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

interface ContentMiscPublicCommunicationLegalsRouteChildren {
  ContentMiscPublicCommunicationLegalsNameRoute: typeof ContentMiscPublicCommunicationLegalsNameRoute;
  ContentMiscPublicCommunicationLegalsIndexRoute: typeof ContentMiscPublicCommunicationLegalsIndexRoute;
}

const ContentMiscPublicCommunicationLegalsRouteChildren: ContentMiscPublicCommunicationLegalsRouteChildren =
  {
    ContentMiscPublicCommunicationLegalsNameRoute:
      ContentMiscPublicCommunicationLegalsNameRoute,
    ContentMiscPublicCommunicationLegalsIndexRoute:
      ContentMiscPublicCommunicationLegalsIndexRoute,
  };

const ContentMiscPublicCommunicationLegalsRouteWithChildren =
  ContentMiscPublicCommunicationLegalsRoute._addFileChildren(
    ContentMiscPublicCommunicationLegalsRouteChildren,
  );

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardDashboardRouteWithChildren;
  '/about': typeof ContentMiscAboutRoute;
  '/b-certificate': typeof ContentMiscBCertificateRoute;
  '/manifesto': typeof ContentMiscManifestoRoute;
  '/node-network': typeof ContentMiscNodeNetworkRoute;
  '/terms-and-conditions': typeof ContentMiscTermsAndConditionsRoute;
  '/under-construction': typeof ContentMiscUnderConstructionRoute;
  '/events/$eventId': typeof ContentEventsEventIdRoute;
  '/dashboard/bookings': typeof DashboardDashboardBookingsRoute;
  '/dashboard/calendar': typeof DashboardDashboardCalendarRoute;
  '/dashboard/courses': typeof DashboardDashboardCoursesRoute;
  '/dashboard/credentials': typeof DashboardDashboardCredentialsRoute;
  '/dashboard/profile': typeof DashboardDashboardProfileRoute;
  '/courses': typeof ContentCoursesIndexRoute;
  '/events': typeof ContentEventsIndexRoute;
  '/resources': typeof ContentResourcesIndexRoute;
  '/tutorials': typeof ContentTutorialsIndexRoute;
  '/bcert-certificates/$certificateId': typeof ContentMiscBcertCertificatesCertificateIdRoute;
  '/exam-certificates/$certificateId': typeof ContentMiscExamCertificatesCertificateIdRoute;
  '/professor/$professorName-$professorId': typeof ContentMiscProfessorProfessorNameProfessorIdRoute;
  '/public-communication/legals': typeof ContentMiscPublicCommunicationLegalsRouteWithChildren;
  '/reset-password/$token': typeof ContentMiscResetPasswordTokenRoute;
  '/validate-email/$token': typeof ContentMiscValidateEmailTokenRoute;
  '/courses/$courseId/$chapterId': typeof ContentCoursesCourseIdChapterIdRoute;
  '/resources/books/$bookName-$bookId': typeof ContentResourcesBooksBookNameBookIdRoute;
  '/resources/builders/$builderName-$builderId': typeof ContentResourcesBuildersBuilderNameBuilderIdRoute;
  '/resources/conferences/$conferenceName-$conferenceId': typeof ContentResourcesConferencesConferenceNameConferenceIdRoute;
  '/resources/glossary/$wordId': typeof ContentResourcesGlossaryWordIdRoute;
  '/resources/newsletters/$newsletterName-$newsletterId': typeof ContentResourcesNewslettersNewsletterNameNewsletterIdRoute;
  '/resources/podcasts/$podcastName-$podcastId': typeof ContentResourcesPodcastsPodcastNamePodcastIdRoute;
  '/dashboard/administration/bookings': typeof DashboardDashboardAdministrationBookingsRoute;
  '/dashboard/administration/role': typeof DashboardDashboardAdministrationRoleRoute;
  '/dashboard/administration/tutorials': typeof DashboardDashboardAdministrationTutorialsRoute;
  '/dashboard/course/$courseId': typeof DashboardDashboardCourseCourseIdRoute;
  '/dashboard/course/completed': typeof DashboardDashboardCourseCompletedRoute;
  '/dashboard/professor/courses': typeof DashboardDashboardProfessorCoursesRoute;
  '/dashboard/professor/profile': typeof DashboardDashboardProfessorProfileRoute;
  '/dashboard/professor/tutorials': typeof DashboardDashboardProfessorTutorialsRoute;
  '/professors': typeof ContentMiscProfessorsIndexRoute;
  '/public-communication': typeof ContentMiscPublicCommunicationIndexRoute;
  '/courses/$courseId': typeof ContentCoursesCourseIdIndexRoute;
  '/resources/bet': typeof ContentResourcesBetIndexRoute;
  '/resources/books': typeof ContentResourcesBooksIndexRoute;
  '/resources/builders': typeof ContentResourcesBuildersIndexRoute;
  '/resources/conferences': typeof ContentResourcesConferencesIndexRoute;
  '/resources/glossary': typeof ContentResourcesGlossaryIndexRoute;
  '/resources/newsletters': typeof ContentResourcesNewslettersIndexRoute;
  '/resources/podcasts': typeof ContentResourcesPodcastsIndexRoute;
  '/tutorials/$category': typeof ContentTutorialsCategoryIndexRoute;
  '/public-communication/legals/$name': typeof ContentMiscPublicCommunicationLegalsNameRoute;
  '/tutorials/$category/$subcategory/$name-$id': typeof ContentTutorialsCategorySubcategoryNameIdRoute;
  '/professors/$category': typeof ContentMiscProfessorsCategoryIndexRoute;
  '/public-communication/blogs-and-news': typeof ContentMiscPublicCommunicationBlogsAndNewsIndexRoute;
  '/public-communication/legals/': typeof ContentMiscPublicCommunicationLegalsIndexRoute;
  '/public-communication/blogs-and-news/$category/$name': typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryNameRoute;
  '/public-communication/blogs-and-news/$category': typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardDashboardRouteWithChildren;
  '/about': typeof ContentMiscAboutRoute;
  '/b-certificate': typeof ContentMiscBCertificateRoute;
  '/manifesto': typeof ContentMiscManifestoRoute;
  '/node-network': typeof ContentMiscNodeNetworkRoute;
  '/terms-and-conditions': typeof ContentMiscTermsAndConditionsRoute;
  '/under-construction': typeof ContentMiscUnderConstructionRoute;
  '/events/$eventId': typeof ContentEventsEventIdRoute;
  '/dashboard/bookings': typeof DashboardDashboardBookingsRoute;
  '/dashboard/calendar': typeof DashboardDashboardCalendarRoute;
  '/dashboard/courses': typeof DashboardDashboardCoursesRoute;
  '/dashboard/credentials': typeof DashboardDashboardCredentialsRoute;
  '/dashboard/profile': typeof DashboardDashboardProfileRoute;
  '/courses': typeof ContentCoursesIndexRoute;
  '/events': typeof ContentEventsIndexRoute;
  '/resources': typeof ContentResourcesIndexRoute;
  '/tutorials': typeof ContentTutorialsIndexRoute;
  '/bcert-certificates/$certificateId': typeof ContentMiscBcertCertificatesCertificateIdRoute;
  '/exam-certificates/$certificateId': typeof ContentMiscExamCertificatesCertificateIdRoute;
  '/professor/$professorName-$professorId': typeof ContentMiscProfessorProfessorNameProfessorIdRoute;
  '/reset-password/$token': typeof ContentMiscResetPasswordTokenRoute;
  '/validate-email/$token': typeof ContentMiscValidateEmailTokenRoute;
  '/courses/$courseId/$chapterId': typeof ContentCoursesCourseIdChapterIdRoute;
  '/resources/books/$bookName-$bookId': typeof ContentResourcesBooksBookNameBookIdRoute;
  '/resources/builders/$builderName-$builderId': typeof ContentResourcesBuildersBuilderNameBuilderIdRoute;
  '/resources/conferences/$conferenceName-$conferenceId': typeof ContentResourcesConferencesConferenceNameConferenceIdRoute;
  '/resources/glossary/$wordId': typeof ContentResourcesGlossaryWordIdRoute;
  '/resources/newsletters/$newsletterName-$newsletterId': typeof ContentResourcesNewslettersNewsletterNameNewsletterIdRoute;
  '/resources/podcasts/$podcastName-$podcastId': typeof ContentResourcesPodcastsPodcastNamePodcastIdRoute;
  '/dashboard/administration/bookings': typeof DashboardDashboardAdministrationBookingsRoute;
  '/dashboard/administration/role': typeof DashboardDashboardAdministrationRoleRoute;
  '/dashboard/administration/tutorials': typeof DashboardDashboardAdministrationTutorialsRoute;
  '/dashboard/course/$courseId': typeof DashboardDashboardCourseCourseIdRoute;
  '/dashboard/course/completed': typeof DashboardDashboardCourseCompletedRoute;
  '/dashboard/professor/courses': typeof DashboardDashboardProfessorCoursesRoute;
  '/dashboard/professor/profile': typeof DashboardDashboardProfessorProfileRoute;
  '/dashboard/professor/tutorials': typeof DashboardDashboardProfessorTutorialsRoute;
  '/professors': typeof ContentMiscProfessorsIndexRoute;
  '/public-communication': typeof ContentMiscPublicCommunicationIndexRoute;
  '/courses/$courseId': typeof ContentCoursesCourseIdIndexRoute;
  '/resources/bet': typeof ContentResourcesBetIndexRoute;
  '/resources/books': typeof ContentResourcesBooksIndexRoute;
  '/resources/builders': typeof ContentResourcesBuildersIndexRoute;
  '/resources/conferences': typeof ContentResourcesConferencesIndexRoute;
  '/resources/glossary': typeof ContentResourcesGlossaryIndexRoute;
  '/resources/newsletters': typeof ContentResourcesNewslettersIndexRoute;
  '/resources/podcasts': typeof ContentResourcesPodcastsIndexRoute;
  '/tutorials/$category': typeof ContentTutorialsCategoryIndexRoute;
  '/public-communication/legals/$name': typeof ContentMiscPublicCommunicationLegalsNameRoute;
  '/tutorials/$category/$subcategory/$name-$id': typeof ContentTutorialsCategorySubcategoryNameIdRoute;
  '/professors/$category': typeof ContentMiscProfessorsCategoryIndexRoute;
  '/public-communication/blogs-and-news': typeof ContentMiscPublicCommunicationBlogsAndNewsIndexRoute;
  '/public-communication/legals': typeof ContentMiscPublicCommunicationLegalsIndexRoute;
  '/public-communication/blogs-and-news/$category/$name': typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryNameRoute;
  '/public-communication/blogs-and-news/$category': typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/dashboard/_dashboard': typeof DashboardDashboardRouteWithChildren;
  '/_content/_misc/about': typeof ContentMiscAboutRoute;
  '/_content/_misc/b-certificate': typeof ContentMiscBCertificateRoute;
  '/_content/_misc/manifesto': typeof ContentMiscManifestoRoute;
  '/_content/_misc/node-network': typeof ContentMiscNodeNetworkRoute;
  '/_content/_misc/terms-and-conditions': typeof ContentMiscTermsAndConditionsRoute;
  '/_content/_misc/under-construction': typeof ContentMiscUnderConstructionRoute;
  '/_content/events/$eventId': typeof ContentEventsEventIdRoute;
  '/dashboard/_dashboard/bookings': typeof DashboardDashboardBookingsRoute;
  '/dashboard/_dashboard/calendar': typeof DashboardDashboardCalendarRoute;
  '/dashboard/_dashboard/courses': typeof DashboardDashboardCoursesRoute;
  '/dashboard/_dashboard/credentials': typeof DashboardDashboardCredentialsRoute;
  '/dashboard/_dashboard/profile': typeof DashboardDashboardProfileRoute;
  '/_content/courses/': typeof ContentCoursesIndexRoute;
  '/_content/events/': typeof ContentEventsIndexRoute;
  '/_content/resources/': typeof ContentResourcesIndexRoute;
  '/_content/tutorials/': typeof ContentTutorialsIndexRoute;
  '/_content/_misc/bcert-certificates/$certificateId': typeof ContentMiscBcertCertificatesCertificateIdRoute;
  '/_content/_misc/exam-certificates/$certificateId': typeof ContentMiscExamCertificatesCertificateIdRoute;
  '/_content/_misc/professor/$professorName-$professorId': typeof ContentMiscProfessorProfessorNameProfessorIdRoute;
  '/_content/_misc/public-communication/legals': typeof ContentMiscPublicCommunicationLegalsRouteWithChildren;
  '/_content/_misc/reset-password/$token': typeof ContentMiscResetPasswordTokenRoute;
  '/_content/_misc/validate-email/$token': typeof ContentMiscValidateEmailTokenRoute;
  '/_content/courses/$courseId/$chapterId': typeof ContentCoursesCourseIdChapterIdRoute;
  '/_content/resources/books/$bookName-$bookId': typeof ContentResourcesBooksBookNameBookIdRoute;
  '/_content/resources/builders/$builderName-$builderId': typeof ContentResourcesBuildersBuilderNameBuilderIdRoute;
  '/_content/resources/conferences/$conferenceName-$conferenceId': typeof ContentResourcesConferencesConferenceNameConferenceIdRoute;
  '/_content/resources/glossary/$wordId': typeof ContentResourcesGlossaryWordIdRoute;
  '/_content/resources/newsletters/$newsletterName-$newsletterId': typeof ContentResourcesNewslettersNewsletterNameNewsletterIdRoute;
  '/_content/resources/podcasts/$podcastName-$podcastId': typeof ContentResourcesPodcastsPodcastNamePodcastIdRoute;
  '/dashboard/_dashboard/administration/bookings': typeof DashboardDashboardAdministrationBookingsRoute;
  '/dashboard/_dashboard/administration/role': typeof DashboardDashboardAdministrationRoleRoute;
  '/dashboard/_dashboard/administration/tutorials': typeof DashboardDashboardAdministrationTutorialsRoute;
  '/dashboard/_dashboard/course/$courseId': typeof DashboardDashboardCourseCourseIdRoute;
  '/dashboard/_dashboard/course/completed': typeof DashboardDashboardCourseCompletedRoute;
  '/dashboard/_dashboard/professor/courses': typeof DashboardDashboardProfessorCoursesRoute;
  '/dashboard/_dashboard/professor/profile': typeof DashboardDashboardProfessorProfileRoute;
  '/dashboard/_dashboard/professor/tutorials': typeof DashboardDashboardProfessorTutorialsRoute;
  '/_content/_misc/professors/': typeof ContentMiscProfessorsIndexRoute;
  '/_content/_misc/public-communication/': typeof ContentMiscPublicCommunicationIndexRoute;
  '/_content/courses/$courseId/': typeof ContentCoursesCourseIdIndexRoute;
  '/_content/resources/bet/': typeof ContentResourcesBetIndexRoute;
  '/_content/resources/books/': typeof ContentResourcesBooksIndexRoute;
  '/_content/resources/builders/': typeof ContentResourcesBuildersIndexRoute;
  '/_content/resources/conferences/': typeof ContentResourcesConferencesIndexRoute;
  '/_content/resources/glossary/': typeof ContentResourcesGlossaryIndexRoute;
  '/_content/resources/newsletters/': typeof ContentResourcesNewslettersIndexRoute;
  '/_content/resources/podcasts/': typeof ContentResourcesPodcastsIndexRoute;
  '/_content/tutorials/$category/': typeof ContentTutorialsCategoryIndexRoute;
  '/_content/_misc/public-communication/legals/$name': typeof ContentMiscPublicCommunicationLegalsNameRoute;
  '/_content/tutorials/$category/$subcategory/$name-$id': typeof ContentTutorialsCategorySubcategoryNameIdRoute;
  '/_content/_misc/professors/$category/': typeof ContentMiscProfessorsCategoryIndexRoute;
  '/_content/_misc/public-communication/blogs-and-news/': typeof ContentMiscPublicCommunicationBlogsAndNewsIndexRoute;
  '/_content/_misc/public-communication/legals/': typeof ContentMiscPublicCommunicationLegalsIndexRoute;
  '/_content/_misc/public-communication/blogs-and-news/$category/$name': typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryNameRoute;
  '/_content/_misc/public-communication/blogs-and-news/$category/': typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/b-certificate'
    | '/manifesto'
    | '/node-network'
    | '/terms-and-conditions'
    | '/under-construction'
    | '/events/$eventId'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/courses'
    | '/dashboard/credentials'
    | '/dashboard/profile'
    | '/courses'
    | '/events'
    | '/resources'
    | '/tutorials'
    | '/bcert-certificates/$certificateId'
    | '/exam-certificates/$certificateId'
    | '/professor/$professorName-$professorId'
    | '/public-communication/legals'
    | '/reset-password/$token'
    | '/validate-email/$token'
    | '/courses/$courseId/$chapterId'
    | '/resources/books/$bookName-$bookId'
    | '/resources/builders/$builderName-$builderId'
    | '/resources/conferences/$conferenceName-$conferenceId'
    | '/resources/glossary/$wordId'
    | '/resources/newsletters/$newsletterName-$newsletterId'
    | '/resources/podcasts/$podcastName-$podcastId'
    | '/dashboard/administration/bookings'
    | '/dashboard/administration/role'
    | '/dashboard/administration/tutorials'
    | '/dashboard/course/$courseId'
    | '/dashboard/course/completed'
    | '/dashboard/professor/courses'
    | '/dashboard/professor/profile'
    | '/dashboard/professor/tutorials'
    | '/professors'
    | '/public-communication'
    | '/courses/$courseId'
    | '/resources/bet'
    | '/resources/books'
    | '/resources/builders'
    | '/resources/conferences'
    | '/resources/glossary'
    | '/resources/newsletters'
    | '/resources/podcasts'
    | '/tutorials/$category'
    | '/public-communication/legals/$name'
    | '/tutorials/$category/$subcategory/$name-$id'
    | '/professors/$category'
    | '/public-communication/blogs-and-news'
    | '/public-communication/legals/'
    | '/public-communication/blogs-and-news/$category/$name'
    | '/public-communication/blogs-and-news/$category';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/b-certificate'
    | '/manifesto'
    | '/node-network'
    | '/terms-and-conditions'
    | '/under-construction'
    | '/events/$eventId'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/courses'
    | '/dashboard/credentials'
    | '/dashboard/profile'
    | '/courses'
    | '/events'
    | '/resources'
    | '/tutorials'
    | '/bcert-certificates/$certificateId'
    | '/exam-certificates/$certificateId'
    | '/professor/$professorName-$professorId'
    | '/reset-password/$token'
    | '/validate-email/$token'
    | '/courses/$courseId/$chapterId'
    | '/resources/books/$bookName-$bookId'
    | '/resources/builders/$builderName-$builderId'
    | '/resources/conferences/$conferenceName-$conferenceId'
    | '/resources/glossary/$wordId'
    | '/resources/newsletters/$newsletterName-$newsletterId'
    | '/resources/podcasts/$podcastName-$podcastId'
    | '/dashboard/administration/bookings'
    | '/dashboard/administration/role'
    | '/dashboard/administration/tutorials'
    | '/dashboard/course/$courseId'
    | '/dashboard/course/completed'
    | '/dashboard/professor/courses'
    | '/dashboard/professor/profile'
    | '/dashboard/professor/tutorials'
    | '/professors'
    | '/public-communication'
    | '/courses/$courseId'
    | '/resources/bet'
    | '/resources/books'
    | '/resources/builders'
    | '/resources/conferences'
    | '/resources/glossary'
    | '/resources/newsletters'
    | '/resources/podcasts'
    | '/tutorials/$category'
    | '/public-communication/legals/$name'
    | '/tutorials/$category/$subcategory/$name-$id'
    | '/professors/$category'
    | '/public-communication/blogs-and-news'
    | '/public-communication/legals'
    | '/public-communication/blogs-and-news/$category/$name'
    | '/public-communication/blogs-and-news/$category';
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/_dashboard'
    | '/_content/_misc/about'
    | '/_content/_misc/b-certificate'
    | '/_content/_misc/manifesto'
    | '/_content/_misc/node-network'
    | '/_content/_misc/terms-and-conditions'
    | '/_content/_misc/under-construction'
    | '/_content/events/$eventId'
    | '/dashboard/_dashboard/bookings'
    | '/dashboard/_dashboard/calendar'
    | '/dashboard/_dashboard/courses'
    | '/dashboard/_dashboard/credentials'
    | '/dashboard/_dashboard/profile'
    | '/_content/courses/'
    | '/_content/events/'
    | '/_content/resources/'
    | '/_content/tutorials/'
    | '/_content/_misc/bcert-certificates/$certificateId'
    | '/_content/_misc/exam-certificates/$certificateId'
    | '/_content/_misc/professor/$professorName-$professorId'
    | '/_content/_misc/public-communication/legals'
    | '/_content/_misc/reset-password/$token'
    | '/_content/_misc/validate-email/$token'
    | '/_content/courses/$courseId/$chapterId'
    | '/_content/resources/books/$bookName-$bookId'
    | '/_content/resources/builders/$builderName-$builderId'
    | '/_content/resources/conferences/$conferenceName-$conferenceId'
    | '/_content/resources/glossary/$wordId'
    | '/_content/resources/newsletters/$newsletterName-$newsletterId'
    | '/_content/resources/podcasts/$podcastName-$podcastId'
    | '/dashboard/_dashboard/administration/bookings'
    | '/dashboard/_dashboard/administration/role'
    | '/dashboard/_dashboard/administration/tutorials'
    | '/dashboard/_dashboard/course/$courseId'
    | '/dashboard/_dashboard/course/completed'
    | '/dashboard/_dashboard/professor/courses'
    | '/dashboard/_dashboard/professor/profile'
    | '/dashboard/_dashboard/professor/tutorials'
    | '/_content/_misc/professors/'
    | '/_content/_misc/public-communication/'
    | '/_content/courses/$courseId/'
    | '/_content/resources/bet/'
    | '/_content/resources/books/'
    | '/_content/resources/builders/'
    | '/_content/resources/conferences/'
    | '/_content/resources/glossary/'
    | '/_content/resources/newsletters/'
    | '/_content/resources/podcasts/'
    | '/_content/tutorials/$category/'
    | '/_content/_misc/public-communication/legals/$name'
    | '/_content/tutorials/$category/$subcategory/$name-$id'
    | '/_content/_misc/professors/$category/'
    | '/_content/_misc/public-communication/blogs-and-news/'
    | '/_content/_misc/public-communication/legals/'
    | '/_content/_misc/public-communication/blogs-and-news/$category/$name'
    | '/_content/_misc/public-communication/blogs-and-news/$category/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
  ContentMiscAboutRoute: typeof ContentMiscAboutRoute;
  ContentMiscBCertificateRoute: typeof ContentMiscBCertificateRoute;
  ContentMiscManifestoRoute: typeof ContentMiscManifestoRoute;
  ContentMiscNodeNetworkRoute: typeof ContentMiscNodeNetworkRoute;
  ContentMiscTermsAndConditionsRoute: typeof ContentMiscTermsAndConditionsRoute;
  ContentMiscUnderConstructionRoute: typeof ContentMiscUnderConstructionRoute;
  ContentEventsEventIdRoute: typeof ContentEventsEventIdRoute;
  ContentCoursesIndexRoute: typeof ContentCoursesIndexRoute;
  ContentEventsIndexRoute: typeof ContentEventsIndexRoute;
  ContentResourcesIndexRoute: typeof ContentResourcesIndexRoute;
  ContentTutorialsIndexRoute: typeof ContentTutorialsIndexRoute;
  ContentMiscBcertCertificatesCertificateIdRoute: typeof ContentMiscBcertCertificatesCertificateIdRoute;
  ContentMiscExamCertificatesCertificateIdRoute: typeof ContentMiscExamCertificatesCertificateIdRoute;
  ContentMiscProfessorProfessorNameProfessorIdRoute: typeof ContentMiscProfessorProfessorNameProfessorIdRoute;
  ContentMiscPublicCommunicationLegalsRoute: typeof ContentMiscPublicCommunicationLegalsRouteWithChildren;
  ContentMiscResetPasswordTokenRoute: typeof ContentMiscResetPasswordTokenRoute;
  ContentMiscValidateEmailTokenRoute: typeof ContentMiscValidateEmailTokenRoute;
  ContentCoursesCourseIdChapterIdRoute: typeof ContentCoursesCourseIdChapterIdRoute;
  ContentResourcesBooksBookNameBookIdRoute: typeof ContentResourcesBooksBookNameBookIdRoute;
  ContentResourcesBuildersBuilderNameBuilderIdRoute: typeof ContentResourcesBuildersBuilderNameBuilderIdRoute;
  ContentResourcesConferencesConferenceNameConferenceIdRoute: typeof ContentResourcesConferencesConferenceNameConferenceIdRoute;
  ContentResourcesGlossaryWordIdRoute: typeof ContentResourcesGlossaryWordIdRoute;
  ContentResourcesNewslettersNewsletterNameNewsletterIdRoute: typeof ContentResourcesNewslettersNewsletterNameNewsletterIdRoute;
  ContentResourcesPodcastsPodcastNamePodcastIdRoute: typeof ContentResourcesPodcastsPodcastNamePodcastIdRoute;
  ContentMiscProfessorsIndexRoute: typeof ContentMiscProfessorsIndexRoute;
  ContentMiscPublicCommunicationIndexRoute: typeof ContentMiscPublicCommunicationIndexRoute;
  ContentCoursesCourseIdIndexRoute: typeof ContentCoursesCourseIdIndexRoute;
  ContentResourcesBetIndexRoute: typeof ContentResourcesBetIndexRoute;
  ContentResourcesBooksIndexRoute: typeof ContentResourcesBooksIndexRoute;
  ContentResourcesBuildersIndexRoute: typeof ContentResourcesBuildersIndexRoute;
  ContentResourcesConferencesIndexRoute: typeof ContentResourcesConferencesIndexRoute;
  ContentResourcesGlossaryIndexRoute: typeof ContentResourcesGlossaryIndexRoute;
  ContentResourcesNewslettersIndexRoute: typeof ContentResourcesNewslettersIndexRoute;
  ContentResourcesPodcastsIndexRoute: typeof ContentResourcesPodcastsIndexRoute;
  ContentTutorialsCategoryIndexRoute: typeof ContentTutorialsCategoryIndexRoute;
  ContentTutorialsCategorySubcategoryNameIdRoute: typeof ContentTutorialsCategorySubcategoryNameIdRoute;
  ContentMiscProfessorsCategoryIndexRoute: typeof ContentMiscProfessorsCategoryIndexRoute;
  ContentMiscPublicCommunicationBlogsAndNewsIndexRoute: typeof ContentMiscPublicCommunicationBlogsAndNewsIndexRoute;
  ContentMiscPublicCommunicationBlogsAndNewsCategoryNameRoute: typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryNameRoute;
  ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexRoute: typeof ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ContentMiscAboutRoute: ContentMiscAboutRoute,
  ContentMiscBCertificateRoute: ContentMiscBCertificateRoute,
  ContentMiscManifestoRoute: ContentMiscManifestoRoute,
  ContentMiscNodeNetworkRoute: ContentMiscNodeNetworkRoute,
  ContentMiscTermsAndConditionsRoute: ContentMiscTermsAndConditionsRoute,
  ContentMiscUnderConstructionRoute: ContentMiscUnderConstructionRoute,
  ContentEventsEventIdRoute: ContentEventsEventIdRoute,
  ContentCoursesIndexRoute: ContentCoursesIndexRoute,
  ContentEventsIndexRoute: ContentEventsIndexRoute,
  ContentResourcesIndexRoute: ContentResourcesIndexRoute,
  ContentTutorialsIndexRoute: ContentTutorialsIndexRoute,
  ContentMiscBcertCertificatesCertificateIdRoute:
    ContentMiscBcertCertificatesCertificateIdRoute,
  ContentMiscExamCertificatesCertificateIdRoute:
    ContentMiscExamCertificatesCertificateIdRoute,
  ContentMiscProfessorProfessorNameProfessorIdRoute:
    ContentMiscProfessorProfessorNameProfessorIdRoute,
  ContentMiscPublicCommunicationLegalsRoute:
    ContentMiscPublicCommunicationLegalsRouteWithChildren,
  ContentMiscResetPasswordTokenRoute: ContentMiscResetPasswordTokenRoute,
  ContentMiscValidateEmailTokenRoute: ContentMiscValidateEmailTokenRoute,
  ContentCoursesCourseIdChapterIdRoute: ContentCoursesCourseIdChapterIdRoute,
  ContentResourcesBooksBookNameBookIdRoute:
    ContentResourcesBooksBookNameBookIdRoute,
  ContentResourcesBuildersBuilderNameBuilderIdRoute:
    ContentResourcesBuildersBuilderNameBuilderIdRoute,
  ContentResourcesConferencesConferenceNameConferenceIdRoute:
    ContentResourcesConferencesConferenceNameConferenceIdRoute,
  ContentResourcesGlossaryWordIdRoute: ContentResourcesGlossaryWordIdRoute,
  ContentResourcesNewslettersNewsletterNameNewsletterIdRoute:
    ContentResourcesNewslettersNewsletterNameNewsletterIdRoute,
  ContentResourcesPodcastsPodcastNamePodcastIdRoute:
    ContentResourcesPodcastsPodcastNamePodcastIdRoute,
  ContentMiscProfessorsIndexRoute: ContentMiscProfessorsIndexRoute,
  ContentMiscPublicCommunicationIndexRoute:
    ContentMiscPublicCommunicationIndexRoute,
  ContentCoursesCourseIdIndexRoute: ContentCoursesCourseIdIndexRoute,
  ContentResourcesBetIndexRoute: ContentResourcesBetIndexRoute,
  ContentResourcesBooksIndexRoute: ContentResourcesBooksIndexRoute,
  ContentResourcesBuildersIndexRoute: ContentResourcesBuildersIndexRoute,
  ContentResourcesConferencesIndexRoute: ContentResourcesConferencesIndexRoute,
  ContentResourcesGlossaryIndexRoute: ContentResourcesGlossaryIndexRoute,
  ContentResourcesNewslettersIndexRoute: ContentResourcesNewslettersIndexRoute,
  ContentResourcesPodcastsIndexRoute: ContentResourcesPodcastsIndexRoute,
  ContentTutorialsCategoryIndexRoute: ContentTutorialsCategoryIndexRoute,
  ContentTutorialsCategorySubcategoryNameIdRoute:
    ContentTutorialsCategorySubcategoryNameIdRoute,
  ContentMiscProfessorsCategoryIndexRoute:
    ContentMiscProfessorsCategoryIndexRoute,
  ContentMiscPublicCommunicationBlogsAndNewsIndexRoute:
    ContentMiscPublicCommunicationBlogsAndNewsIndexRoute,
  ContentMiscPublicCommunicationBlogsAndNewsCategoryNameRoute:
    ContentMiscPublicCommunicationBlogsAndNewsCategoryNameRoute,
  ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexRoute:
    ContentMiscPublicCommunicationBlogsAndNewsCategoryIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/_content/_misc/about",
        "/_content/_misc/b-certificate",
        "/_content/_misc/manifesto",
        "/_content/_misc/node-network",
        "/_content/_misc/terms-and-conditions",
        "/_content/_misc/under-construction",
        "/_content/events/$eventId",
        "/_content/courses/",
        "/_content/events/",
        "/_content/resources/",
        "/_content/tutorials/",
        "/_content/_misc/bcert-certificates/$certificateId",
        "/_content/_misc/exam-certificates/$certificateId",
        "/_content/_misc/professor/$professorName-$professorId",
        "/_content/_misc/public-communication/legals",
        "/_content/_misc/reset-password/$token",
        "/_content/_misc/validate-email/$token",
        "/_content/courses/$courseId/$chapterId",
        "/_content/resources/books/$bookName-$bookId",
        "/_content/resources/builders/$builderName-$builderId",
        "/_content/resources/conferences/$conferenceName-$conferenceId",
        "/_content/resources/glossary/$wordId",
        "/_content/resources/newsletters/$newsletterName-$newsletterId",
        "/_content/resources/podcasts/$podcastName-$podcastId",
        "/_content/_misc/professors/",
        "/_content/_misc/public-communication/",
        "/_content/courses/$courseId/",
        "/_content/resources/bet/",
        "/_content/resources/books/",
        "/_content/resources/builders/",
        "/_content/resources/conferences/",
        "/_content/resources/glossary/",
        "/_content/resources/newsletters/",
        "/_content/resources/podcasts/",
        "/_content/tutorials/$category/",
        "/_content/tutorials/$category/$subcategory/$name-$id",
        "/_content/_misc/professors/$category/",
        "/_content/_misc/public-communication/blogs-and-news/",
        "/_content/_misc/public-communication/blogs-and-news/$category/$name",
        "/_content/_misc/public-communication/blogs-and-news/$category/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_dashboard"
      ]
    },
    "/dashboard/_dashboard": {
      "filePath": "dashboard/_dashboard.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_dashboard/bookings",
        "/dashboard/_dashboard/calendar",
        "/dashboard/_dashboard/courses",
        "/dashboard/_dashboard/credentials",
        "/dashboard/_dashboard/profile",
        "/dashboard/_dashboard/administration/bookings",
        "/dashboard/_dashboard/administration/role",
        "/dashboard/_dashboard/administration/tutorials",
        "/dashboard/_dashboard/course/$courseId",
        "/dashboard/_dashboard/course/completed",
        "/dashboard/_dashboard/professor/courses",
        "/dashboard/_dashboard/professor/profile",
        "/dashboard/_dashboard/professor/tutorials"
      ]
    },
    "/_content/_misc/about": {
      "filePath": "_content/_misc/about.tsx"
    },
    "/_content/_misc/b-certificate": {
      "filePath": "_content/_misc/b-certificate.tsx"
    },
    "/_content/_misc/manifesto": {
      "filePath": "_content/_misc/manifesto.tsx"
    },
    "/_content/_misc/node-network": {
      "filePath": "_content/_misc/node-network.tsx"
    },
    "/_content/_misc/terms-and-conditions": {
      "filePath": "_content/_misc/terms-and-conditions.tsx"
    },
    "/_content/_misc/under-construction": {
      "filePath": "_content/_misc/under-construction.tsx"
    },
    "/_content/events/$eventId": {
      "filePath": "_content/events/$eventId.tsx"
    },
    "/dashboard/_dashboard/bookings": {
      "filePath": "dashboard/_dashboard/bookings.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/calendar": {
      "filePath": "dashboard/_dashboard/calendar.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/courses": {
      "filePath": "dashboard/_dashboard/courses.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/credentials": {
      "filePath": "dashboard/_dashboard/credentials.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/profile": {
      "filePath": "dashboard/_dashboard/profile.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/_content/courses/": {
      "filePath": "_content/courses/index.tsx"
    },
    "/_content/events/": {
      "filePath": "_content/events/index.tsx"
    },
    "/_content/resources/": {
      "filePath": "_content/resources/index.tsx"
    },
    "/_content/tutorials/": {
      "filePath": "_content/tutorials/index.tsx"
    },
    "/_content/_misc/bcert-certificates/$certificateId": {
      "filePath": "_content/_misc/bcert-certificates.$certificateId.tsx"
    },
    "/_content/_misc/exam-certificates/$certificateId": {
      "filePath": "_content/_misc/exam-certificates.$certificateId.tsx"
    },
    "/_content/_misc/professor/$professorName-$professorId": {
      "filePath": "_content/_misc/professor.$professorName-$professorId.tsx"
    },
    "/_content/_misc/public-communication/legals": {
      "filePath": "_content/_misc/public-communication/legals.tsx",
      "children": [
        "/_content/_misc/public-communication/legals/$name",
        "/_content/_misc/public-communication/legals/"
      ]
    },
    "/_content/_misc/reset-password/$token": {
      "filePath": "_content/_misc/reset-password.$token.tsx"
    },
    "/_content/_misc/validate-email/$token": {
      "filePath": "_content/_misc/validate-email.$token.tsx"
    },
    "/_content/courses/$courseId/$chapterId": {
      "filePath": "_content/courses/$courseId/$chapterId.tsx"
    },
    "/_content/resources/books/$bookName-$bookId": {
      "filePath": "_content/resources/books/$bookName-$bookId.tsx"
    },
    "/_content/resources/builders/$builderName-$builderId": {
      "filePath": "_content/resources/builders/$builderName-$builderId.tsx"
    },
    "/_content/resources/conferences/$conferenceName-$conferenceId": {
      "filePath": "_content/resources/conferences/$conferenceName-$conferenceId.tsx"
    },
    "/_content/resources/glossary/$wordId": {
      "filePath": "_content/resources/glossary/$wordId.tsx"
    },
    "/_content/resources/newsletters/$newsletterName-$newsletterId": {
      "filePath": "_content/resources/newsletters/$newsletterName-$newsletterId.tsx"
    },
    "/_content/resources/podcasts/$podcastName-$podcastId": {
      "filePath": "_content/resources/podcasts/$podcastName-$podcastId.tsx"
    },
    "/dashboard/_dashboard/administration/bookings": {
      "filePath": "dashboard/_dashboard/administration/bookings.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/administration/role": {
      "filePath": "dashboard/_dashboard/administration/role.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/administration/tutorials": {
      "filePath": "dashboard/_dashboard/administration/tutorials.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/course/$courseId": {
      "filePath": "dashboard/_dashboard/course/$courseId.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/course/completed": {
      "filePath": "dashboard/_dashboard/course/completed.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/professor/courses": {
      "filePath": "dashboard/_dashboard/professor/courses.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/professor/profile": {
      "filePath": "dashboard/_dashboard/professor/profile.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/professor/tutorials": {
      "filePath": "dashboard/_dashboard/professor/tutorials.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/_content/_misc/professors/": {
      "filePath": "_content/_misc/professors/index.tsx"
    },
    "/_content/_misc/public-communication/": {
      "filePath": "_content/_misc/public-communication/index.tsx"
    },
    "/_content/courses/$courseId/": {
      "filePath": "_content/courses/$courseId/index.tsx"
    },
    "/_content/resources/bet/": {
      "filePath": "_content/resources/bet/index.tsx"
    },
    "/_content/resources/books/": {
      "filePath": "_content/resources/books/index.tsx"
    },
    "/_content/resources/builders/": {
      "filePath": "_content/resources/builders/index.tsx"
    },
    "/_content/resources/conferences/": {
      "filePath": "_content/resources/conferences/index.tsx"
    },
    "/_content/resources/glossary/": {
      "filePath": "_content/resources/glossary/index.tsx"
    },
    "/_content/resources/newsletters/": {
      "filePath": "_content/resources/newsletters/index.tsx"
    },
    "/_content/resources/podcasts/": {
      "filePath": "_content/resources/podcasts/index.tsx"
    },
    "/_content/tutorials/$category/": {
      "filePath": "_content/tutorials/$category/index.tsx"
    },
    "/_content/_misc/public-communication/legals/$name": {
      "filePath": "_content/_misc/public-communication/legals/$name.tsx",
      "parent": "/_content/_misc/public-communication/legals"
    },
    "/_content/tutorials/$category/$subcategory/$name-$id": {
      "filePath": "_content/tutorials/$category/$subcategory.$name-$id.tsx"
    },
    "/_content/_misc/professors/$category/": {
      "filePath": "_content/_misc/professors/$category/index.tsx"
    },
    "/_content/_misc/public-communication/blogs-and-news/": {
      "filePath": "_content/_misc/public-communication/blogs-and-news/index.tsx"
    },
    "/_content/_misc/public-communication/legals/": {
      "filePath": "_content/_misc/public-communication/legals/index.tsx",
      "parent": "/_content/_misc/public-communication/legals"
    },
    "/_content/_misc/public-communication/blogs-and-news/$category/$name": {
      "filePath": "_content/_misc/public-communication/blogs-and-news/$category/$name.tsx"
    },
    "/_content/_misc/public-communication/blogs-and-news/$category/": {
      "filePath": "_content/_misc/public-communication/blogs-and-news/$category/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
