// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CoursesId } from '../content/Courses';

import type { AccountsUid } from './Accounts';

/** Identifier type for users.course_completed_chapters */
export type CourseCompletedChaptersChapter = number;

/** Represents the table users.course_completed_chapters */
export default interface CourseCompletedChapters {
  uid: AccountsUid;

  course_id: CoursesId;

  chapter: CourseCompletedChaptersChapter;

  completed_at: number;
}

/** Represents the initializer for the table users.course_completed_chapters */
export interface CourseCompletedChaptersInitializer {
  uid: AccountsUid;

  course_id: CoursesId;

  chapter: CourseCompletedChaptersChapter;

  /** Default value: now() */
  completed_at?: number;
}

/** Represents the mutator for the table users.course_completed_chapters */
export interface CourseCompletedChaptersMutator {
  uid?: AccountsUid;

  course_id?: CoursesId;

  chapter?: CourseCompletedChaptersChapter;

  completed_at?: number;
}
