// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsUid } from './Accounts';

/** Identifier type for users.lud4_public_keys */
export type Lud4PublicKeysId = string;

/** Represents the table users.lud4_public_keys */
export default interface Lud4PublicKeys {
  id: Lud4PublicKeysId;

  uid: AccountsUid;

  public_key: string;

  created_at: number;

  updated_at: number;
}

/** Represents the initializer for the table users.lud4_public_keys */
export interface Lud4PublicKeysInitializer {
  /** Default value: gen_random_uuid() */
  id?: Lud4PublicKeysId;

  uid: AccountsUid;

  public_key: string;

  /** Default value: now() */
  created_at?: number;

  /** Default value: now() */
  updated_at?: number;
}

/** Represents the mutator for the table users.lud4_public_keys */
export interface Lud4PublicKeysMutator {
  id?: Lud4PublicKeysId;

  uid?: AccountsUid;

  public_key?: string;

  created_at?: number;

  updated_at?: number;
}
