load_module /usr/lib/nginx/modules/ngx_http_image_filter_module.so;

worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 4096;
    multi_accept on;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 4096;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_types text/plain text/css application/javascript application/json application/xml+rss;

    open_file_cache max=100000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    # Use docker's DNS resolver
    resolver 127.0.0.11 ipv6=off;

    map "$time_iso8601:$msec" $time_iso8601_ms {
        ~(.+)\+00:00:.+(\..+) $1$2Z;
        ~(.+)(\+.+):.+(\..+)  $1$3$2;
    }

    map "$http_cf_connecting_ip" $real_ip {
        default $http_cf_connecting_ip;
        "" $http_x_real_ip;
    }

    # Detect commit hash in query string (e.g. ?c=abcdef1234567890abcdef1234567890abcdef12)
    map $args $commit_hash {
        "~c=([a-f0-9]{40})" $1;
    }

    map $args $quality {
        ~q=(\d+)  $1;
        default   100;
    }

    map $args $width {
        ~w=(\d+)  $1;
        default   1280;
    }

    map $args $height {
        ~h=(\d+)  $1;
        default   -;
    }

    log_format  main  '$time_iso8601_ms $request_id $real_ip $request_method "$request_uri" '
                      '$status $request_time $body_bytes_sent "$http_referer" "$http_user_agent"';

    access_log /var/log/nginx/access.log main;

    server {
        listen 80;
        server_name _;

        root /var/www/cdn;

        expires 1d; # 86400 seconds

        # Cache-Control: public, stale-while-revalidate: 30 days, stale-if-error: 30 days
        add_header Cache-Control "public, stale-while-revalidate=2592000, stale-if-error=2592000";

        open_file_cache_errors off;
        open_file_cache_valid 60m;
        open_file_cache_min_uses 3;
        open_file_cache max=10000 inactive=60m;

        gzip_static on;
        gzip_vary on;
        gzip_disable "MSIE [1-6]\.(?!.*SV1)";

        # Image resizing
        location ~* \.(?:jpg|jpeg|webp)$ {
            expires 1M;
            access_log off;

            if ($commit_hash) {
                expires 1y;
                add_header Cache-Control "public, immutable, stale-while-revalidate=31536000, stale-if-error=31536000";
                add_header X-Hash-Match $commit_hash;
            }

            image_filter_buffer 100M;

            image_filter resize $width $height;

            image_filter_webp_quality $quality;
            image_filter_jpeg_quality $quality;
        }

        # Match assets provided with a commit cache key in the search path
        location / {
            if ($commit_hash) {
                expires 1y;
                add_header Cache-Control "public, immutable, stale-while-revalidate=31536000, stale-if-error=31536000";
                add_header X-Hash-Match $commit_hash;
            }
        }
    }
}
