ALTER TABLE "content"."bet" ADD CONSTRAINT "bet_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."bet_localized" ADD CONSTRAINT "bet_localized_bet_id_bet_resource_id_fk" FOREIGN KEY ("bet_id") REFERENCES "content"."bet"("resource_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."bet_view_url" ADD CONSTRAINT "bet_view_url_bet_id_bet_resource_id_fk" FOREIGN KEY ("bet_id") REFERENCES "content"."bet"("resource_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."books" ADD CONSTRAINT "books_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."books_localized" ADD CONSTRAINT "books_localized_book_id_books_resource_id_fk" FOREIGN KEY ("book_id") REFERENCES "content"."books"("resource_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."conferences" ADD CONSTRAINT "conferences_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."conferences_stages" ADD CONSTRAINT "conferences_stages_conference_id_conferences_resource_id_fk" FOREIGN KEY ("conference_id") REFERENCES "content"."conferences"("resource_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."glossary_words" ADD CONSTRAINT "glossary_words_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."glossary_words_localized" ADD CONSTRAINT "glossary_words_localized_glossary_word_id_glossary_words_resource_id_fk" FOREIGN KEY ("glossary_word_id") REFERENCES "content"."glossary_words"("resource_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."movies" ADD CONSTRAINT "movies_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."newsletters" ADD CONSTRAINT "newsletters_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."podcasts" ADD CONSTRAINT "podcasts_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."projects" ADD CONSTRAINT "projects_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."proofreading" ADD CONSTRAINT "proofreading_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."resource_tags" ADD CONSTRAINT "resource_tags_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "content"."youtube_channels" ADD CONSTRAINT "youtube_channels_resource_id_resources_id_fk" FOREIGN KEY ("resource_id") REFERENCES "content"."resources"("id") ON DELETE cascade ON UPDATE cascade;