/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LangIndexRouteImport } from './routes/$lang/index';
import { Route as LangContentIndexRouteImport } from './routes/$lang/content/index';
import { Route as LangContentEditRouteImport } from './routes/$lang/content/edit';
import { Route as LangContentCreateRouteImport } from './routes/$lang/content/create';
import { Route as LangContentTranslateIndexRouteImport } from './routes/$lang/content/translate/index';
import { Route as LangContentTranslateCourseIdRouteImport } from './routes/$lang/content/translate/$courseId';
import { Route as LangContentTranslateCourseIdChapterIdRouteImport } from './routes/$lang/content/translate/$courseId/$chapterId';
import { Route as LangContentTranslateCourseIdChapterIdCompareSlideIndexRouteImport } from './routes/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex';

const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any);
const LangContentIndexRoute = LangContentIndexRouteImport.update({
  id: '/$lang/content/',
  path: '/$lang/content/',
  getParentRoute: () => rootRouteImport,
} as any);
const LangContentEditRoute = LangContentEditRouteImport.update({
  id: '/$lang/content/edit',
  path: '/$lang/content/edit',
  getParentRoute: () => rootRouteImport,
} as any);
const LangContentCreateRoute = LangContentCreateRouteImport.update({
  id: '/$lang/content/create',
  path: '/$lang/content/create',
  getParentRoute: () => rootRouteImport,
} as any);
const LangContentTranslateIndexRoute =
  LangContentTranslateIndexRouteImport.update({
    id: '/$lang/content/translate/',
    path: '/$lang/content/translate/',
    getParentRoute: () => rootRouteImport,
  } as any);
const LangContentTranslateCourseIdRoute =
  LangContentTranslateCourseIdRouteImport.update({
    id: '/$lang/content/translate/$courseId',
    path: '/$lang/content/translate/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any);
const LangContentTranslateCourseIdChapterIdRoute =
  LangContentTranslateCourseIdChapterIdRouteImport.update({
    id: '/$chapterId',
    path: '/$chapterId',
    getParentRoute: () => LangContentTranslateCourseIdRoute,
  } as any);
const LangContentTranslateCourseIdChapterIdCompareSlideIndexRoute =
  LangContentTranslateCourseIdChapterIdCompareSlideIndexRouteImport.update({
    id: '/compare/$slideIndex',
    path: '/compare/$slideIndex',
    getParentRoute: () => LangContentTranslateCourseIdChapterIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/$lang': typeof LangIndexRoute;
  '/$lang/content/create': typeof LangContentCreateRoute;
  '/$lang/content/edit': typeof LangContentEditRoute;
  '/$lang/content': typeof LangContentIndexRoute;
  '/$lang/content/translate/$courseId': typeof LangContentTranslateCourseIdRouteWithChildren;
  '/$lang/content/translate': typeof LangContentTranslateIndexRoute;
  '/$lang/content/translate/$courseId/$chapterId': typeof LangContentTranslateCourseIdChapterIdRouteWithChildren;
  '/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex': typeof LangContentTranslateCourseIdChapterIdCompareSlideIndexRoute;
}
export interface FileRoutesByTo {
  '/$lang': typeof LangIndexRoute;
  '/$lang/content/create': typeof LangContentCreateRoute;
  '/$lang/content/edit': typeof LangContentEditRoute;
  '/$lang/content': typeof LangContentIndexRoute;
  '/$lang/content/translate/$courseId': typeof LangContentTranslateCourseIdRouteWithChildren;
  '/$lang/content/translate': typeof LangContentTranslateIndexRoute;
  '/$lang/content/translate/$courseId/$chapterId': typeof LangContentTranslateCourseIdChapterIdRouteWithChildren;
  '/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex': typeof LangContentTranslateCourseIdChapterIdCompareSlideIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/$lang/': typeof LangIndexRoute;
  '/$lang/content/create': typeof LangContentCreateRoute;
  '/$lang/content/edit': typeof LangContentEditRoute;
  '/$lang/content/': typeof LangContentIndexRoute;
  '/$lang/content/translate/$courseId': typeof LangContentTranslateCourseIdRouteWithChildren;
  '/$lang/content/translate/': typeof LangContentTranslateIndexRoute;
  '/$lang/content/translate/$courseId/$chapterId': typeof LangContentTranslateCourseIdChapterIdRouteWithChildren;
  '/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex': typeof LangContentTranslateCourseIdChapterIdCompareSlideIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/$lang'
    | '/$lang/content/create'
    | '/$lang/content/edit'
    | '/$lang/content'
    | '/$lang/content/translate/$courseId'
    | '/$lang/content/translate'
    | '/$lang/content/translate/$courseId/$chapterId'
    | '/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/$lang'
    | '/$lang/content/create'
    | '/$lang/content/edit'
    | '/$lang/content'
    | '/$lang/content/translate/$courseId'
    | '/$lang/content/translate'
    | '/$lang/content/translate/$courseId/$chapterId'
    | '/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex';
  id:
    | '__root__'
    | '/$lang/'
    | '/$lang/content/create'
    | '/$lang/content/edit'
    | '/$lang/content/'
    | '/$lang/content/translate/$courseId'
    | '/$lang/content/translate/'
    | '/$lang/content/translate/$courseId/$chapterId'
    | '/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  LangIndexRoute: typeof LangIndexRoute;
  LangContentCreateRoute: typeof LangContentCreateRoute;
  LangContentEditRoute: typeof LangContentEditRoute;
  LangContentIndexRoute: typeof LangContentIndexRoute;
  LangContentTranslateCourseIdRoute: typeof LangContentTranslateCourseIdRouteWithChildren;
  LangContentTranslateIndexRoute: typeof LangContentTranslateIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang/': {
      id: '/$lang/';
      path: '/$lang';
      fullPath: '/$lang';
      preLoaderRoute: typeof LangIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang/content/': {
      id: '/$lang/content/';
      path: '/$lang/content';
      fullPath: '/$lang/content';
      preLoaderRoute: typeof LangContentIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang/content/edit': {
      id: '/$lang/content/edit';
      path: '/$lang/content/edit';
      fullPath: '/$lang/content/edit';
      preLoaderRoute: typeof LangContentEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang/content/create': {
      id: '/$lang/content/create';
      path: '/$lang/content/create';
      fullPath: '/$lang/content/create';
      preLoaderRoute: typeof LangContentCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang/content/translate/': {
      id: '/$lang/content/translate/';
      path: '/$lang/content/translate';
      fullPath: '/$lang/content/translate';
      preLoaderRoute: typeof LangContentTranslateIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang/content/translate/$courseId': {
      id: '/$lang/content/translate/$courseId';
      path: '/$lang/content/translate/$courseId';
      fullPath: '/$lang/content/translate/$courseId';
      preLoaderRoute: typeof LangContentTranslateCourseIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang/content/translate/$courseId/$chapterId': {
      id: '/$lang/content/translate/$courseId/$chapterId';
      path: '/$chapterId';
      fullPath: '/$lang/content/translate/$courseId/$chapterId';
      preLoaderRoute: typeof LangContentTranslateCourseIdChapterIdRouteImport;
      parentRoute: typeof LangContentTranslateCourseIdRoute;
    };
    '/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex': {
      id: '/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex';
      path: '/compare/$slideIndex';
      fullPath: '/$lang/content/translate/$courseId/$chapterId/compare/$slideIndex';
      preLoaderRoute: typeof LangContentTranslateCourseIdChapterIdCompareSlideIndexRouteImport;
      parentRoute: typeof LangContentTranslateCourseIdChapterIdRoute;
    };
  }
}

interface LangContentTranslateCourseIdChapterIdRouteChildren {
  LangContentTranslateCourseIdChapterIdCompareSlideIndexRoute: typeof LangContentTranslateCourseIdChapterIdCompareSlideIndexRoute;
}

const LangContentTranslateCourseIdChapterIdRouteChildren: LangContentTranslateCourseIdChapterIdRouteChildren =
  {
    LangContentTranslateCourseIdChapterIdCompareSlideIndexRoute:
      LangContentTranslateCourseIdChapterIdCompareSlideIndexRoute,
  };

const LangContentTranslateCourseIdChapterIdRouteWithChildren =
  LangContentTranslateCourseIdChapterIdRoute._addFileChildren(
    LangContentTranslateCourseIdChapterIdRouteChildren,
  );

interface LangContentTranslateCourseIdRouteChildren {
  LangContentTranslateCourseIdChapterIdRoute: typeof LangContentTranslateCourseIdChapterIdRouteWithChildren;
}

const LangContentTranslateCourseIdRouteChildren: LangContentTranslateCourseIdRouteChildren =
  {
    LangContentTranslateCourseIdChapterIdRoute:
      LangContentTranslateCourseIdChapterIdRouteWithChildren,
  };

const LangContentTranslateCourseIdRouteWithChildren =
  LangContentTranslateCourseIdRoute._addFileChildren(
    LangContentTranslateCourseIdRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangContentCreateRoute: LangContentCreateRoute,
  LangContentEditRoute: LangContentEditRoute,
  LangContentIndexRoute: LangContentIndexRoute,
  LangContentTranslateCourseIdRoute:
    LangContentTranslateCourseIdRouteWithChildren,
  LangContentTranslateIndexRoute: LangContentTranslateIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
