// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsUid } from './Accounts.js';
import type { CoursesId } from '../content/Courses.js';

/** Identifier type for users.course_payment */
export type CoursePaymentPaymentId = string;

/** Represents the table users.course_payment */
export default interface CoursePayment {
  uid: AccountsUid;

  course_id: CoursesId;

  payment_id: CoursePaymentPaymentId;

  payment_status: string;

  amount: number;

  invoice_url?: string;

  last_updated: number;
}

/** Represents the initializer for the table users.course_payment */
export interface CoursePaymentInitializer {
  uid: AccountsUid;

  course_id: CoursesId;

  payment_id: CoursePaymentPaymentId;

  payment_status: string;

  amount: number;

  invoice_url?: string;

  /** Default value: now() */
  last_updated?: number;
}

/** Represents the mutator for the table users.course_payment */
export interface CoursePaymentMutator {
  uid?: AccountsUid;

  course_id?: CoursesId;

  payment_id?: CoursePaymentPaymentId;

  payment_status?: string;

  amount?: number;

  invoice_url?: string;

  last_updated?: number;
}
