// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type {
  CourseChaptersLocalizedChapter,
  CourseChaptersLocalizedLanguage,
} from '../content/CourseChaptersLocalized';
import type { CoursesId } from '../content/Courses';

import type { AccountsUid } from './Accounts';

/** Represents the table users.course_completed_chapters */
export default interface CourseCompletedChapters {
  uid: AccountsUid;

  course_id: CoursesId | CoursesId;

  language: CourseChaptersLocalizedLanguage;

  chapter: CourseChaptersLocalizedChapter;

  completed_at: number;
}

/** Represents the initializer for the table users.course_completed_chapters */
export interface CourseCompletedChaptersInitializer {
  uid: AccountsUid;

  course_id: CoursesId | CoursesId;

  language: CourseChaptersLocalizedLanguage;

  chapter: CourseChaptersLocalizedChapter;

  /** Default value: now() */
  completed_at?: number;
}

/** Represents the mutator for the table users.course_completed_chapters */
export interface CourseCompletedChaptersMutator {
  uid?: AccountsUid;

  course_id?: CoursesId | CoursesId;

  language?: CourseChaptersLocalizedLanguage;

  chapter?: CourseChaptersLocalizedChapter;

  completed_at?: number;
}
