// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CoursesId } from '../content/Courses';

import type { AccountsUid } from './Accounts';

/** Identifier type for users.course_progress */
export type CourseProgressLanguage = string;

/** Represents the table users.course_progress */
export default interface CourseProgress {
  uid: AccountsUid;

  course_id: CoursesId;

  language: CourseProgressLanguage;

  completed_chapters_count: number;

  last_updated: number;

  progress_percentage: number;
}

/** Represents the initializer for the table users.course_progress */
export interface CourseProgressInitializer {
  uid: AccountsUid;

  course_id: CoursesId;

  language: CourseProgressLanguage;

  /** Default value: 0 */
  completed_chapters_count?: number;

  /** Default value: now() */
  last_updated?: number;

  /** Default value: 0 */
  progress_percentage?: number;
}

/** Represents the mutator for the table users.course_progress */
export interface CourseProgressMutator {
  uid?: AccountsUid;

  course_id?: CoursesId;

  language?: CourseProgressLanguage;

  completed_chapters_count?: number;

  last_updated?: number;

  progress_percentage?: number;
}
