/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as BlogIndexRouteImport } from './routes/blog/index';
import { Route as BlogCategoryRouteImport } from './routes/blog/$category';
import { Route as BlogArticleBlogNameBlogIdRouteImport } from './routes/blog/article/$blogName-$blogId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any);
const BlogCategoryRoute = BlogCategoryRouteImport.update({
  id: '/blog/$category',
  path: '/blog/$category',
  getParentRoute: () => rootRouteImport,
} as any);
const BlogArticleBlogNameBlogIdRoute =
  BlogArticleBlogNameBlogIdRouteImport.update({
    id: '/blog/article/$blogName-$blogId',
    path: '/blog/article/$blogName-$blogId',
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/blog/$category': typeof BlogCategoryRoute;
  '/blog': typeof BlogIndexRoute;
  '/blog/article/$blogName-$blogId': typeof BlogArticleBlogNameBlogIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/blog/$category': typeof BlogCategoryRoute;
  '/blog': typeof BlogIndexRoute;
  '/blog/article/$blogName-$blogId': typeof BlogArticleBlogNameBlogIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/blog/$category': typeof BlogCategoryRoute;
  '/blog/': typeof BlogIndexRoute;
  '/blog/article/$blogName-$blogId': typeof BlogArticleBlogNameBlogIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/blog/$category'
    | '/blog'
    | '/blog/article/$blogName-$blogId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/blog/$category' | '/blog' | '/blog/article/$blogName-$blogId';
  id:
    | '__root__'
    | '/'
    | '/blog/$category'
    | '/blog/'
    | '/blog/article/$blogName-$blogId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BlogCategoryRoute: typeof BlogCategoryRoute;
  BlogIndexRoute: typeof BlogIndexRoute;
  BlogArticleBlogNameBlogIdRoute: typeof BlogArticleBlogNameBlogIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/blog/': {
      id: '/blog/';
      path: '/blog';
      fullPath: '/blog';
      preLoaderRoute: typeof BlogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/blog/$category': {
      id: '/blog/$category';
      path: '/blog/$category';
      fullPath: '/blog/$category';
      preLoaderRoute: typeof BlogCategoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/blog/article/$blogName-$blogId': {
      id: '/blog/article/$blogName-$blogId';
      path: '/blog/article/$blogName-$blogId';
      fullPath: '/blog/article/$blogName-$blogId';
      preLoaderRoute: typeof BlogArticleBlogNameBlogIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogCategoryRoute: BlogCategoryRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogArticleBlogNameBlogIdRoute: BlogArticleBlogNameBlogIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
