/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as HubsRouteImport } from './routes/hubs';
import { Route as FundsRouteImport } from './routes/funds';
import { Route as AcademyRouteImport } from './routes/academy';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as NewsIndexRouteImport } from './routes/news/index';
import { Route as LegalIndexRouteImport } from './routes/legal/index';
import { Route as NewsCategoryRouteImport } from './routes/news/$category';
import { Route as LegalNameRouteImport } from './routes/legal/$name';
import { Route as NewsArticleArticleSlugRouteImport } from './routes/news/article/$articleSlug';

const HubsRoute = HubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => rootRouteImport,
} as any);
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any);
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any);
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any);
const NewsCategoryRoute = NewsCategoryRouteImport.update({
  id: '/news/$category',
  path: '/news/$category',
  getParentRoute: () => rootRouteImport,
} as any);
const LegalNameRoute = LegalNameRouteImport.update({
  id: '/legal/$name',
  path: '/legal/$name',
  getParentRoute: () => rootRouteImport,
} as any);
const NewsArticleArticleSlugRoute = NewsArticleArticleSlugRouteImport.update({
  id: '/news/article/$articleSlug',
  path: '/news/article/$articleSlug',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/academy': typeof AcademyRoute;
  '/funds': typeof FundsRoute;
  '/hubs': typeof HubsRoute;
  '/legal/$name': typeof LegalNameRoute;
  '/news/$category': typeof NewsCategoryRoute;
  '/legal/': typeof LegalIndexRoute;
  '/news/': typeof NewsIndexRoute;
  '/news/article/$articleSlug': typeof NewsArticleArticleSlugRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/academy': typeof AcademyRoute;
  '/funds': typeof FundsRoute;
  '/hubs': typeof HubsRoute;
  '/legal/$name': typeof LegalNameRoute;
  '/news/$category': typeof NewsCategoryRoute;
  '/legal': typeof LegalIndexRoute;
  '/news': typeof NewsIndexRoute;
  '/news/article/$articleSlug': typeof NewsArticleArticleSlugRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/academy': typeof AcademyRoute;
  '/funds': typeof FundsRoute;
  '/hubs': typeof HubsRoute;
  '/legal/$name': typeof LegalNameRoute;
  '/news/$category': typeof NewsCategoryRoute;
  '/legal/': typeof LegalIndexRoute;
  '/news/': typeof NewsIndexRoute;
  '/news/article/$articleSlug': typeof NewsArticleArticleSlugRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/funds'
    | '/hubs'
    | '/legal/$name'
    | '/news/$category'
    | '/legal/'
    | '/news/'
    | '/news/article/$articleSlug';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/funds'
    | '/hubs'
    | '/legal/$name'
    | '/news/$category'
    | '/legal'
    | '/news'
    | '/news/article/$articleSlug';
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/funds'
    | '/hubs'
    | '/legal/$name'
    | '/news/$category'
    | '/legal/'
    | '/news/'
    | '/news/article/$articleSlug';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  AcademyRoute: typeof AcademyRoute;
  FundsRoute: typeof FundsRoute;
  HubsRoute: typeof HubsRoute;
  LegalNameRoute: typeof LegalNameRoute;
  NewsCategoryRoute: typeof NewsCategoryRoute;
  LegalIndexRoute: typeof LegalIndexRoute;
  NewsIndexRoute: typeof NewsIndexRoute;
  NewsArticleArticleSlugRoute: typeof NewsArticleArticleSlugRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hubs': {
      id: '/hubs';
      path: '/hubs';
      fullPath: '/hubs';
      preLoaderRoute: typeof HubsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/funds': {
      id: '/funds';
      path: '/funds';
      fullPath: '/funds';
      preLoaderRoute: typeof FundsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/academy': {
      id: '/academy';
      path: '/academy';
      fullPath: '/academy';
      preLoaderRoute: typeof AcademyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/news/': {
      id: '/news/';
      path: '/news';
      fullPath: '/news/';
      preLoaderRoute: typeof NewsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/legal/': {
      id: '/legal/';
      path: '/legal';
      fullPath: '/legal/';
      preLoaderRoute: typeof LegalIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/news/$category': {
      id: '/news/$category';
      path: '/news/$category';
      fullPath: '/news/$category';
      preLoaderRoute: typeof NewsCategoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/legal/$name': {
      id: '/legal/$name';
      path: '/legal/$name';
      fullPath: '/legal/$name';
      preLoaderRoute: typeof LegalNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/news/article/$articleSlug': {
      id: '/news/article/$articleSlug';
      path: '/news/article/$articleSlug';
      fullPath: '/news/article/$articleSlug';
      preLoaderRoute: typeof NewsArticleArticleSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  FundsRoute: FundsRoute,
  HubsRoute: HubsRoute,
  LegalNameRoute: LegalNameRoute,
  NewsCategoryRoute: NewsCategoryRoute,
  LegalIndexRoute: LegalIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  NewsArticleArticleSlugRoute: NewsArticleArticleSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
