// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources';

/** Identifier type for content.contributions */
export type ContributionsLanguage = string;

/** Represents the table content.contributions */
export default interface Contributions {
  resource_id: ResourcesId;

  language: ContributionsLanguage;

  contributor_id: string;
}

/** Represents the initializer for the table content.contributions */
export interface ContributionsInitializer {
  resource_id: ResourcesId;

  language: ContributionsLanguage;

  contributor_id: string;
}

/** Represents the mutator for the table content.contributions */
export interface ContributionsMutator {
  resource_id?: ResourcesId;

  language?: ContributionsLanguage;

  contributor_id?: string;
}
