// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for content.contributors */
export type ContributorsId = string;

/** Represents the table content.contributors */
export default interface Contributors {
  id: ContributorsId;
}

/** Represents the initializer for the table content.contributors */
export interface ContributorsInitializer {
  id: ContributorsId;
}

/** Represents the mutator for the table content.contributors */
export interface ContributorsMutator {
  id?: ContributorsId;
}
