// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CoursesId } from './Courses';
import type { CoursePartsPart } from './CourseParts';

/** Identifier type for content.course_chapters */
export type CourseChaptersChapter = number;

/** Represents the table content.course_chapters */
export default interface CourseChapters {
  course_id: CoursesId;

  part: CoursePartsPart;

  chapter: CourseChaptersChapter;
}

/** Represents the initializer for the table content.course_chapters */
export interface CourseChaptersInitializer {
  course_id: CoursesId;

  part: CoursePartsPart;

  chapter: CourseChaptersChapter;
}

/** Represents the mutator for the table content.course_chapters */
export interface CourseChaptersMutator {
  course_id?: CoursesId;

  part?: CoursePartsPart;

  chapter?: CourseChaptersChapter;
}
