// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CoursesId } from './Courses';
import type { CoursePartsPart } from './CourseParts';
import type { CoursesLocalizedLanguage } from './CoursesLocalized';

/** Represents the table content.course_parts_localized */
export default interface CoursePartsLocalized {
  course_id: CoursesId | CoursesId;

  part: CoursePartsPart;

  language: CoursesLocalizedLanguage;

  title: string;
}

/** Represents the initializer for the table content.course_parts_localized */
export interface CoursePartsLocalizedInitializer {
  course_id: CoursesId | CoursesId;

  part: CoursePartsPart;

  language: CoursesLocalizedLanguage;

  title: string;
}

/** Represents the mutator for the table content.course_parts_localized */
export interface CoursePartsLocalizedMutator {
  course_id?: CoursesId | CoursesId;

  part?: CoursePartsPart;

  language?: CoursesLocalizedLanguage;

  title?: string;
}
