// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources';

/** Represents the table content.podcasts */
export default interface Podcasts {
  resource_id: ResourcesId;

  language: string;

  name: string;

  host: string;

  description?: string;

  website_url?: string;

  twitter_url?: string;

  podcast_url?: string;

  nostr?: string;
}

/** Represents the initializer for the table content.podcasts */
export interface PodcastsInitializer {
  resource_id: ResourcesId;

  language: string;

  name: string;

  host: string;

  description?: string;

  website_url?: string;

  twitter_url?: string;

  podcast_url?: string;

  nostr?: string;
}

/** Represents the mutator for the table content.podcasts */
export interface PodcastsMutator {
  resource_id?: ResourcesId;

  language?: string;

  name?: string;

  host?: string;

  description?: string;

  website_url?: string;

  twitter_url?: string;

  podcast_url?: string;

  nostr?: string;
}
