// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ContributorsId } from './Contributors';

/** Identifier type for content.professors */
export type ProfessorsId = number;

/** Represents the table content.professors */
export default interface Professors {
  id: ProfessorsId;

  path: string;

  name: string;

  company?: string;

  affiliations?: string[];

  contributor_id: ContributorsId;

  website_url?: string;

  twitter_url?: string;

  github_url?: string;

  nostr?: string;

  lightning_address?: string;

  lnurl_pay?: string;

  paynym?: string;

  silent_payment?: string;

  tips_url?: string;

  last_updated: number;

  last_commit: string;
}

/** Represents the initializer for the table content.professors */
export interface ProfessorsInitializer {
  /** Default value: nextval('content.professors_id_seq'::regclass) */
  id?: ProfessorsId;

  path: string;

  name: string;

  company?: string;

  affiliations?: string[];

  contributor_id: ContributorsId;

  website_url?: string;

  twitter_url?: string;

  github_url?: string;

  nostr?: string;

  lightning_address?: string;

  lnurl_pay?: string;

  paynym?: string;

  silent_payment?: string;

  tips_url?: string;

  /** Default value: now() */
  last_updated?: number;

  last_commit: string;
}

/** Represents the mutator for the table content.professors */
export interface ProfessorsMutator {
  id?: ProfessorsId;

  path?: string;

  name?: string;

  company?: string;

  affiliations?: string[];

  contributor_id?: ContributorsId;

  website_url?: string;

  twitter_url?: string;

  github_url?: string;

  nostr?: string;

  lightning_address?: string;

  lnurl_pay?: string;

  paynym?: string;

  silent_payment?: string;

  tips_url?: string;

  last_updated?: number;

  last_commit?: string;
}
