// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { QuizQuestionsId } from './QuizQuestions';

/** Identifier type for content.quiz_questions_localized */
export type QuizQuestionsLocalizedLanguage = string;

/** Represents the table content.quiz_questions_localized */
export default interface QuizQuestionsLocalized {
  quiz_question_id: QuizQuestionsId;

  language: QuizQuestionsLocalizedLanguage;

  question: string;

  answer: string;

  wrong_answers: string[];

  explanation?: string;
}

/** Represents the initializer for the table content.quiz_questions_localized */
export interface QuizQuestionsLocalizedInitializer {
  quiz_question_id: QuizQuestionsId;

  language: QuizQuestionsLocalizedLanguage;

  question: string;

  answer: string;

  wrong_answers: string[];

  explanation?: string;
}

/** Represents the mutator for the table content.quiz_questions_localized */
export interface QuizQuestionsLocalizedMutator {
  quiz_question_id?: QuizQuestionsId;

  language?: QuizQuestionsLocalizedLanguage;

  question?: string;

  answer?: string;

  wrong_answers?: string[];

  explanation?: string;
}
