// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CoursesId } from './Courses';
import type { CoursePartsPart } from './CourseParts';
import type { CourseChaptersChapter } from './CourseChapters';

/** Identifier type for content.quizzes */
export type QuizzesId = number;

/** Represents the table content.quizzes */
export default interface Quizzes {
  id: QuizzesId;

  course_id: CoursesId;

  part: CoursePartsPart;

  chapter: CourseChaptersChapter;

  difficulty: string;

  author?: string;

  duration?: number;

  last_updated: number;

  last_commit: string;
}

/** Represents the initializer for the table content.quizzes */
export interface QuizzesInitializer {
  id: QuizzesId;

  course_id: CoursesId;

  part: CoursePartsPart;

  chapter: CourseChaptersChapter;

  difficulty: string;

  author?: string;

  duration?: number;

  /** Default value: now() */
  last_updated?: number;

  last_commit: string;
}

/** Represents the mutator for the table content.quizzes */
export interface QuizzesMutator {
  id?: QuizzesId;

  course_id?: CoursesId;

  part?: CoursePartsPart;

  chapter?: CourseChaptersChapter;

  difficulty?: string;

  author?: string;

  duration?: number;

  last_updated?: number;

  last_commit?: string;
}
