// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { QuizQuestionsId } from './QuizQuestions';
import type { TagsId } from './Tags';

/** Represents the table content.quiz_question_tags */
export default interface QuizQuestionTags {
  quiz_question_id: QuizQuestionsId;

  tag_id: TagsId;
}

/** Represents the initializer for the table content.quiz_question_tags */
export interface QuizQuestionTagsInitializer {
  quiz_question_id: QuizQuestionsId;

  tag_id: TagsId;
}

/** Represents the mutator for the table content.quiz_question_tags */
export interface QuizQuestionTagsMutator {
  quiz_question_id?: QuizQuestionsId;

  tag_id?: TagsId;
}
