// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { QuizzesId } from './Quizzes';

/** Identifier type for content.quizzes_localized */
export type QuizzesLocalizedLanguage = string;

/** Represents the table content.quizzes_localized */
export default interface QuizzesLocalized {
  quiz_id: QuizzesId;

  language: QuizzesLocalizedLanguage;

  question: string;

  answer: string;

  wrong_answers: string[];

  explanation: string;
}

/** Represents the initializer for the table content.quizzes_localized */
export interface QuizzesLocalizedInitializer {
  quiz_id: QuizzesId;

  language: QuizzesLocalizedLanguage;

  question: string;

  answer: string;

  wrong_answers: string[];

  explanation: string;
}

/** Represents the mutator for the table content.quizzes_localized */
export interface QuizzesLocalizedMutator {
  quiz_id?: QuizzesId;

  language?: QuizzesLocalizedLanguage;

  question?: string;

  answer?: string;

  wrong_answers?: string[];

  explanation?: string;
}
