// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { QuizzesId } from './Quizzes';
import type { TagsId } from './Tags';

/** Represents the table content.quiz_tags */
export default interface QuizTags {
  quiz_id: QuizzesId;

  tag_id: TagsId;
}

/** Represents the initializer for the table content.quiz_tags */
export interface QuizTagsInitializer {
  quiz_id: QuizzesId;

  tag_id: TagsId;
}

/** Represents the mutator for the table content.quiz_tags */
export interface QuizTagsMutator {
  quiz_id?: QuizzesId;

  tag_id?: TagsId;
}
