// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TutorialsId } from './Tutorials';
import type { ContributorsId } from './Contributors';

/** Represents the table content.tutorial_credits */
export default interface TutorialCredits {
  tutorial_id: TutorialsId;

  contributor_id?: ContributorsId;

  name?: string;

  link?: string;

  lightning_address?: string;

  lnurl_pay?: string;

  paynym?: string;

  silent_payment?: string;

  tips_url?: string;
}

/** Represents the initializer for the table content.tutorial_credits */
export interface TutorialCreditsInitializer {
  tutorial_id: TutorialsId;

  contributor_id?: ContributorsId;

  name?: string;

  link?: string;

  lightning_address?: string;

  lnurl_pay?: string;

  paynym?: string;

  silent_payment?: string;

  tips_url?: string;
}

/** Represents the mutator for the table content.tutorial_credits */
export interface TutorialCreditsMutator {
  tutorial_id?: TutorialsId;

  contributor_id?: ContributorsId;

  name?: string;

  link?: string;

  lightning_address?: string;

  lnurl_pay?: string;

  paynym?: string;

  silent_payment?: string;

  tips_url?: string;
}
