name: CI/CD

on:
  push:
    branches:
      - ci-refactoring
      - mainnet
      - testnet
      - dev
  pull_request:

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build_base:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.ref != 'weblate-tr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set Docker image metadata for base
        uses: docker/metadata-action@v5
        id: meta-base
        with:
          images: ghcr.io/planb-network/blms-base
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Build and push Docker image for base
        uses: docker/bake-action@v6
        with:
          push: true
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta-base.outputs.bake-file }}
          targets: base

  build_api:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.ref != 'weblate-tr'
    runs-on: ubuntu-latest
    needs: build_base
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set Docker image metadata for api
        uses: docker/metadata-action@v5
        id: meta-api
        with:
          images: ghcr.io/planb-network/blms-api
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Build and push Docker image for api
        uses: docker/bake-action@v6
        with:
          push: true
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta-api.outputs.bake-file }}
          targets: api

  build_web:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.ref != 'weblate-tr'
    runs-on: ubuntu-latest
    needs: build_base
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set Docker image metadata for web
        uses: docker/metadata-action@v5
        id: meta-web
        with:
          images: ghcr.io/planb-network/blms-web
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Build and push Docker image for web
        uses: docker/bake-action@v6
        with:
          push: true
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta-web.outputs.bake-file }}
          targets: web
