# https://vector.dev/docs/reference/configuration/
data_dir: '/var/lib/vector'

api:
  enabled: true
  address: 0.0.0.0:8686

# https://vector.dev/docs/reference/configuration/sources/docker_logs/
# Ingest data by tailing one or more files
sources:
  docker:
    type: 'docker_logs'

# Structure and parse via Vector's Remap Language
transforms:
  empty_message_filter:
    inputs:
      - docker
    type: 'filter'
    condition:  |
      message = string(.message) ?? ""
      length(strip_whitespace(message)) > 0
  docker_remap:
    inputs:
      - empty_message_filter
    type: 'remap'
    source: |
      del(.stream)
      del(.source_type)
      .service = del(.label."com.docker.compose.service") # api / academy / ...
      .project = del(.label."com.docker.compose.project") # mainnet / testnet
      .container_number = del(.label."com.docker.compose.container-number")
      .platform = "Docker"
      del(.label)

  api_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "api"'

  api_remap:
    inputs:
      - api_filter
    type: 'remap'
    source: | # Replace "@blms/api:dev: " with "" (dev only, appended by turbo)
      .message = replace!(.message, "@blms/api:dev: ", "")

      # Parse scope ([request], [cron], etc.)
      scope_match, scope_err = parse_regex(.message, r'^\[(?P<scope>[^\]]+)\]')
      if scope_err == null {
        .scope = scope_match.scope
      }

      # Get request_id, request_ip, request_session, request_uid
      if starts_with(.message, "[request]") {
        parsed, err = parse_regex(.message, r'^\[request\] (?P<request_id>[a-f0-9]{16})(?P<tags>[^ ]*)')

        if err == null {
          .request_id = parsed.request_id

          # Parse IP
          ip_match, ip_err = parse_regex(parsed.tags, r'\|ip=(?P<ip>[^|]+)')
          if ip_err == null {
            .request_ip = ip_match.ip
          }

          # Parse session
          session_match, session_err = parse_regex(parsed.tags, r'\|session=(?P<session>[^|]+)')
          if session_err == null {
            .request_session = session_match.session
          }

          # Parse uid
          uid_match, uid_err = parse_regex(parsed.tags, r'\|uid=(?P<uid>[^|]+)')
          if uid_err == null {
            .request_uid = uid_match.uid
          }
        }
      }

      # Replace [request] request_id|ip=...|session=...|uid=... with "[request] request_id"
      .message = replace(.message, r'\[request\] (?P<rid>[a-f0-9]{16})[^ ]*', "[request] $$rid")


  api_multiline_merge:
    inputs:
      - api_remap
    type: 'reduce'
    group_by: [".container_id"]
    starts_when: |
      message = string(.message) ?? ""
      !match(message, r'^[ \t\n]') && !match(message, r'^[ \t]*[}\]][ \t]*$')
    expire_after_ms: 200
    merge_strategies:
      message: 'concat_newline'

  api_light_remap:
    inputs:
      - api_remap
    type: 'remap'
    source: | # Keep only message and timestamp
      .old = del(.)
      .message = format_timestamp!(.old.timestamp, "%Y-%m-%dT%H:%M:%S%.3fZ") + " " + .old.message ?? ""
      del(.old)

  # academy logs
  academy_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "academy"'

  academy_remap:
    inputs:
      - academy_filter
    type: 'remap'
    source: |
      # Replace prepending iso date (academy is an nginx service in production)
      .message = replace!(.message, r'^[\d-]+T[\d:.]+Z\s+', "")
      .message = replace(.message, r'^[\d\/]+ [\d:.]+ ', "")
      # Remove turbo dev tag
      .message = replace(.message, "@blms/academy:dev: ", "")

  academy_remap_filter_empty:
    inputs:
      - academy_remap
    type: 'filter'
    condition:  |
      message = string(.message) ?? ""
      length(strip_whitespace(message)) > 0

  academy_light_remap:
    inputs:
      - academy_remap_filter_empty
    type: 'remap'
    source: | # Keep only message and timestamp
      .old = del(.)
      .message = format_timestamp!(.old.timestamp, "%Y-%m-%dT%H:%M:%S%.3fZ") + " " + .old.message ?? ""
      del(.old)

  # Grafana logs
  grafana_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "grafana"'

  grafana_remap:
    inputs:
      - grafana_filter
    type: 'remap'
    source: | # Replace prepending iso date, log level and service
      .message = replace!(.message, r't=[\d-]+T[\d:.]+Z level=\S+\s+', "")

  # CDN Logs (nginx)
  cdn_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "cdn"'

  cdn_remap:
    inputs:
      - cdn_filter
    type: 'remap'
    source: | # Replace prepending iso date
      .message = replace!(.message, r'^[\d-]+T[\d:.]+Z\s+', "")
      .message = replace(.message, r'^[\d\/]+ [\d:.]+ ', "")

  # Traefik logs
  traefik_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "traefik"'

  traefik_remap:
    inputs:
      - traefik_filter
    type: 'remap'
    source: | # Replace prepending iso date
      .message = replace!(.message, r'^time=".+Z" level=\S+\s+', "")

  # Typesense logs
  typesense_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "typesense"'

  typesense_remap:
    inputs:
      - typesense_filter
    type: 'remap'
    source: | # Replace Level + Date + ? (e.g., "I20251028 07:46:52.010643 262")
      .message = replace!(.message, r'^[I][\d]{8} [\d:.]+\s+[\d]+', "INFO")
      .message = replace(.message, r'^[W][\d]{8} [\d:.]+\s+[\d]+', "WARN")
      .message = replace(.message, r'^[E][\d]{8} [\d:.]+\s+[\d]+', "ERROR")
      .message = replace(.message, r'^[F][\d]{8} [\d:.]+\s+[\d]+', "FATAL")

  # Onlyoffice logs
  onlyoffice_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "onlyoffice"'

  onlyoffice_remap:
    inputs:
      - onlyoffice_filter
    type: 'remap'
    source: | # noop
      #

  # Contribute logs
  contribute_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "contribute"'

  contribute_remap:
    inputs:
      - contribute_filter
    type: 'remap'
    source: | # Replace "@blms/contribute:dev: " with "" (dev only, appended by turbo)
      .message = replace!(.message, "@blms/contribute:dev: ", "")

  # Network logs
  network_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "network"'

  network_remap:
    inputs:
      - network_filter
    type: 'remap'
    source: | # Replace "@blms/network:dev: " with "" (dev only, appended by turbo)
      .message = replace!(.message, "@blms/network:dev: ", "")

  # Pear-Sync logs
  pear_sync_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "pear-sync"'

  pear_sync_remap:
    inputs:
      - pear_sync_filter
    type: 'remap'
    source: | # noop
      #

  # Quickwit logs
  quickwit_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "quickwit"'

  quickwit_remap:
    inputs:
      - quickwit_filter
    type: 'remap'
    source:
      | # Remove ANSI escape codes for color formatting & prepending iso date
      .message = replace!(.message, r'\x1b\[[0-9;]*m', "")
      .message = replace(.message, r'^[\d-]+T[\d:.]+Z\s+', "")

  # Prometheus logs
  prometheus_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "prometheus"'

  prometheus_remap:
    inputs:
      - prometheus_filter
    type: 'remap'
    source: | # Replace prepending iso date
      .message = replace!(.message, r'^ts=[\d-]+T[\d:.]+Z\s+', "")

  # Postgres logs
  postgres_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: |
      .service == "postgres"

  postgres_remap:
    inputs:
      - postgres_filter
    type: 'remap'
    source: | # Replace prepending iso date and log level
      .message = replace!(.message, r'^[\d-]{10} [\d:.]+ UTC\s+\[\d+\]\s+[A-Z]+:\s+', "")

  postgres_remap_filter_empty:
    inputs:
      - postgres_remap
    type: 'filter'
    condition:  |
      message = string(.message) ?? ""
      length(strip_whitespace(message)) > 0

  postgres_multiline_merge:
    inputs:
      - postgres_remap_filter_empty
    type: 'reduce'
    group_by: [".container_id"]
    starts_when: |
      message = string(.message) ?? ""
      !match(message, r'^[ \t\n]')
    expire_after_ms: 200
    merge_strategies:
      message: 'concat_newline'

  postgres_light_remap:
    inputs:
      - postgres_remap_filter_empty
    type: 'remap'
    source: | # Keep only message and timestamp
      .old = del(.)
      .message = format_timestamp!(.old.timestamp, "%Y-%m-%dT%H:%M:%S%.3fZ") + " " + .old.message ?? ""
      del(.old)

  # Seed logs
  seed_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "seed"'

  seed_remap:
    inputs:
      - seed_filter
    type: 'remap'
    source: | # Replace prepending iso date
      .message = replace!(.message, r'^\s?[\d-]+T[\d:.]+Z\s+', "")

  seed_light_remap:
    inputs:
      - seed_remap
    type: 'remap'
    source: | # Keep only message and timestamp
      .old = del(.)
      .message = format_timestamp!(.old.timestamp, "%Y-%m-%dT%H:%M:%S%.3fZ") + " " + .old.message ?? ""
      del(.old)

  # Merge all remaps into one
  all_remap:
    inputs:
      - academy_remap_filter_empty
      - cdn_remap
      - api_multiline_merge
      - postgres_multiline_merge
      - seed_remap
      - traefik_remap
      - grafana_remap
      - typesense_remap
      - onlyoffice_remap
      - contribute_remap
      - network_remap
      - pear_sync_remap
      - quickwit_remap
      - prometheus_remap
    type: 'remap'
    source: | # noop
      #

# Send structured data to a short-term storage
sinks:
  raw:
    inputs:
      - docker
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/raw.log'
    encoding:
      codec: json

  raw_s3:
    inputs:
      - docker
    type: 'aws_s3'
    endpoint: ${S3_LOG_ENDPOINT}
    bucket: ${S3_LOG_BUCKET}
    region: ${S3_LOG_REGION}
    key_prefix: vector/%Y-%m-%d/raw.
    compression: gzip
    content_encoding: gzip
    content_type: application/gzip
    filename_append_uuid: false
    filename_extension: log.json.gz
    filename_time_format: '%Y-%m-%dT%Hh%Mm%Ss%3f'
    encoding:
      codec: json
    auth:
      access_key_id: ${S3_LOG_ACCESS_KEY}
      secret_access_key: ${S3_LOG_SECRET_KEY}

  compose:
    inputs:
      - all_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/remap.log'
    encoding:
      codec: json

  # Send logs to S3
  remap_s3:
    inputs:
      - all_remap
    type: 'aws_s3'
    endpoint: ${S3_LOG_ENDPOINT}
    bucket: ${S3_LOG_BUCKET}
    region: ${S3_LOG_REGION}
    key_prefix: vector/%Y-%m-%d/remap.
    compression: gzip
    content_encoding: gzip
    content_type: application/gzip
    filename_append_uuid: false
    filename_extension: log.json.gz
    filename_time_format: '%Y-%m-%dT%Hh%Mm%Ss%3f'
    encoding:
      codec: json
    auth:
      access_key_id: ${S3_LOG_ACCESS_KEY}
      secret_access_key: ${S3_LOG_SECRET_KEY}

  # API output
  api:
    inputs:
      - api_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/full/api.log'
    encoding:
      codec: json

  api_light:
    inputs:
      - api_light_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/light/api.log'
    encoding:
      codec: text

  # Academy output
  academy:
    inputs:
      - academy_remap_filter_empty
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/full/academy.log'
    encoding:
      codec: json

  academy_light:
    inputs:
      - academy_light_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/light/academy.log'
    encoding:
      codec: text

  # Postgres output
  postgres:
    inputs:
      - postgres_remap_filter_empty
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/full/postgres.log'
    encoding:
      codec: json

  postgres_light:
    inputs:
      - postgres_light_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/light/postgres.log'
    encoding:
      codec: text

  # Seed output
  seed:
    inputs:
      - seed_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/full/seed.log'
    encoding:
      codec: json

  seed_light:
    inputs:
      - seed_light_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/light/seed.log'
    encoding:
      codec: text

  # Send logs to Quickwit
  quickwit_http:
    type: http
    method: post
    encoding:
      codec: json
    framing:
      method: newline_delimited
    inputs:
      - all_remap
    uri: 'http://quickwit:7280/api/v1/logs/ingest'
